/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateStageDto,
  Match,
  Stage,
  UpdateStageDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create stage for session
 */
export type stageControllerCreateResponse201 = {
  data: Stage
  status: 201
}
    
export type stageControllerCreateResponseSuccess = (stageControllerCreateResponse201) & {
  headers: Headers;
};
;

export type stageControllerCreateResponse = (stageControllerCreateResponseSuccess)

export const getStageControllerCreateUrl = (eventId: unknown,
    sessionId: string,) => {


  

  return `/events/${eventId}/sessions/${sessionId}/stages`
}

export const stageControllerCreate = async (eventId: unknown,
    sessionId: string,
    createStageDto: CreateStageDto, options?: RequestInit): Promise<stageControllerCreateResponse> => {
  
  return defaultMutator<stageControllerCreateResponse>(getStageControllerCreateUrl(eventId,sessionId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStageDto,)
  }
);}




export const getStageControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerCreate>>, TError,{eventId: unknown;sessionId: string;data: CreateStageDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof stageControllerCreate>>, TError,{eventId: unknown;sessionId: string;data: CreateStageDto}, TContext> => {

const mutationKey = ['stageControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stageControllerCreate>>, {eventId: unknown;sessionId: string;data: CreateStageDto}> = (props) => {
          const {eventId,sessionId,data} = props ?? {};

          return  stageControllerCreate(eventId,sessionId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StageControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof stageControllerCreate>>>
    export type StageControllerCreateMutationBody = CreateStageDto
    export type StageControllerCreateMutationError = unknown

    /**
 * @summary Create stage for session
 */
export const useStageControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerCreate>>, TError,{eventId: unknown;sessionId: string;data: CreateStageDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stageControllerCreate>>,
        TError,
        {eventId: unknown;sessionId: string;data: CreateStageDto},
        TContext
      > => {
      return useMutation(getStageControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all stages for session
 */
export type stageControllerFindAllBySessionResponse200 = {
  data: Stage[]
  status: 200
}
    
export type stageControllerFindAllBySessionResponseSuccess = (stageControllerFindAllBySessionResponse200) & {
  headers: Headers;
};
;

export type stageControllerFindAllBySessionResponse = (stageControllerFindAllBySessionResponseSuccess)

export const getStageControllerFindAllBySessionUrl = (eventId: unknown,
    sessionId: string,) => {


  

  return `/events/${eventId}/sessions/${sessionId}/stages`
}

export const stageControllerFindAllBySession = async (eventId: unknown,
    sessionId: string, options?: RequestInit): Promise<stageControllerFindAllBySessionResponse> => {
  
  return defaultMutator<stageControllerFindAllBySessionResponse>(getStageControllerFindAllBySessionUrl(eventId,sessionId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getStageControllerFindAllBySessionQueryKey = (eventId: unknown,
    sessionId: string,) => {
    return [
    `/events/${eventId}/sessions/${sessionId}/stages`
    ] as const;
    }

    
export const getStageControllerFindAllBySessionQueryOptions = <TData = Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError = unknown>(eventId: unknown,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStageControllerFindAllBySessionQueryKey(eventId,sessionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof stageControllerFindAllBySession>>> = ({ signal }) => stageControllerFindAllBySession(eventId,sessionId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId && sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StageControllerFindAllBySessionQueryResult = NonNullable<Awaited<ReturnType<typeof stageControllerFindAllBySession>>>
export type StageControllerFindAllBySessionQueryError = unknown


export function useStageControllerFindAllBySession<TData = Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError = unknown>(
 eventId: unknown,
    sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof stageControllerFindAllBySession>>,
          TError,
          Awaited<ReturnType<typeof stageControllerFindAllBySession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStageControllerFindAllBySession<TData = Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError = unknown>(
 eventId: unknown,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof stageControllerFindAllBySession>>,
          TError,
          Awaited<ReturnType<typeof stageControllerFindAllBySession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStageControllerFindAllBySession<TData = Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError = unknown>(
 eventId: unknown,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all stages for session
 */

export function useStageControllerFindAllBySession<TData = Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError = unknown>(
 eventId: unknown,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindAllBySession>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStageControllerFindAllBySessionQueryOptions(eventId,sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get stage by ID
 */
export type stageControllerFindOneResponse200 = {
  data: Stage
  status: 200
}
    
export type stageControllerFindOneResponseSuccess = (stageControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type stageControllerFindOneResponse = (stageControllerFindOneResponseSuccess)

export const getStageControllerFindOneUrl = (eventId: unknown,
    stageId: string,) => {


  

  return `/events/${eventId}/stages/${stageId}`
}

export const stageControllerFindOne = async (eventId: unknown,
    stageId: string, options?: RequestInit): Promise<stageControllerFindOneResponse> => {
  
  return defaultMutator<stageControllerFindOneResponse>(getStageControllerFindOneUrl(eventId,stageId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getStageControllerFindOneQueryKey = (eventId: unknown,
    stageId: string,) => {
    return [
    `/events/${eventId}/stages/${stageId}`
    ] as const;
    }

    
export const getStageControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof stageControllerFindOne>>, TError = unknown>(eventId: unknown,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStageControllerFindOneQueryKey(eventId,stageId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof stageControllerFindOne>>> = ({ signal }) => stageControllerFindOne(eventId,stageId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId && stageId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StageControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof stageControllerFindOne>>>
export type StageControllerFindOneQueryError = unknown


export function useStageControllerFindOne<TData = Awaited<ReturnType<typeof stageControllerFindOne>>, TError = unknown>(
 eventId: unknown,
    stageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof stageControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof stageControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStageControllerFindOne<TData = Awaited<ReturnType<typeof stageControllerFindOne>>, TError = unknown>(
 eventId: unknown,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof stageControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof stageControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStageControllerFindOne<TData = Awaited<ReturnType<typeof stageControllerFindOne>>, TError = unknown>(
 eventId: unknown,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get stage by ID
 */

export function useStageControllerFindOne<TData = Awaited<ReturnType<typeof stageControllerFindOne>>, TError = unknown>(
 eventId: unknown,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStageControllerFindOneQueryOptions(eventId,stageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update stage
 */
export type stageControllerUpdateResponse200 = {
  data: Stage
  status: 200
}
    
export type stageControllerUpdateResponseSuccess = (stageControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type stageControllerUpdateResponse = (stageControllerUpdateResponseSuccess)

export const getStageControllerUpdateUrl = (eventId: unknown,
    stageId: string,) => {


  

  return `/events/${eventId}/stages/${stageId}`
}

export const stageControllerUpdate = async (eventId: unknown,
    stageId: string,
    updateStageDto: UpdateStageDto, options?: RequestInit): Promise<stageControllerUpdateResponse> => {
  
  return defaultMutator<stageControllerUpdateResponse>(getStageControllerUpdateUrl(eventId,stageId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStageDto,)
  }
);}




export const getStageControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerUpdate>>, TError,{eventId: unknown;stageId: string;data: UpdateStageDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof stageControllerUpdate>>, TError,{eventId: unknown;stageId: string;data: UpdateStageDto}, TContext> => {

const mutationKey = ['stageControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stageControllerUpdate>>, {eventId: unknown;stageId: string;data: UpdateStageDto}> = (props) => {
          const {eventId,stageId,data} = props ?? {};

          return  stageControllerUpdate(eventId,stageId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StageControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof stageControllerUpdate>>>
    export type StageControllerUpdateMutationBody = UpdateStageDto
    export type StageControllerUpdateMutationError = unknown

    /**
 * @summary Update stage
 */
export const useStageControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerUpdate>>, TError,{eventId: unknown;stageId: string;data: UpdateStageDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stageControllerUpdate>>,
        TError,
        {eventId: unknown;stageId: string;data: UpdateStageDto},
        TContext
      > => {
      return useMutation(getStageControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete stage
 */
export type stageControllerRemoveResponse200 = {
  data: void
  status: 200
}
    
export type stageControllerRemoveResponseSuccess = (stageControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type stageControllerRemoveResponse = (stageControllerRemoveResponseSuccess)

export const getStageControllerRemoveUrl = (eventId: unknown,
    stageId: string,) => {


  

  return `/events/${eventId}/stages/${stageId}`
}

export const stageControllerRemove = async (eventId: unknown,
    stageId: string, options?: RequestInit): Promise<stageControllerRemoveResponse> => {
  
  return defaultMutator<stageControllerRemoveResponse>(getStageControllerRemoveUrl(eventId,stageId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getStageControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerRemove>>, TError,{eventId: unknown;stageId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof stageControllerRemove>>, TError,{eventId: unknown;stageId: string}, TContext> => {

const mutationKey = ['stageControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stageControllerRemove>>, {eventId: unknown;stageId: string}> = (props) => {
          const {eventId,stageId} = props ?? {};

          return  stageControllerRemove(eventId,stageId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StageControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof stageControllerRemove>>>
    
    export type StageControllerRemoveMutationError = unknown

    /**
 * @summary Delete stage
 */
export const useStageControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerRemove>>, TError,{eventId: unknown;stageId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stageControllerRemove>>,
        TError,
        {eventId: unknown;stageId: string},
        TContext
      > => {
      return useMutation(getStageControllerRemoveMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all matches for a stage
 */
export type stageControllerFindMatchesByStageResponse200 = {
  data: Match[]
  status: 200
}
    
export type stageControllerFindMatchesByStageResponseSuccess = (stageControllerFindMatchesByStageResponse200) & {
  headers: Headers;
};
;

export type stageControllerFindMatchesByStageResponse = (stageControllerFindMatchesByStageResponseSuccess)

export const getStageControllerFindMatchesByStageUrl = (eventId: unknown,
    stageId: string,) => {


  

  return `/events/${eventId}/stages/${stageId}/matches`
}

export const stageControllerFindMatchesByStage = async (eventId: unknown,
    stageId: string, options?: RequestInit): Promise<stageControllerFindMatchesByStageResponse> => {
  
  return defaultMutator<stageControllerFindMatchesByStageResponse>(getStageControllerFindMatchesByStageUrl(eventId,stageId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getStageControllerFindMatchesByStageQueryKey = (eventId: unknown,
    stageId: string,) => {
    return [
    `/events/${eventId}/stages/${stageId}/matches`
    ] as const;
    }

    
export const getStageControllerFindMatchesByStageQueryOptions = <TData = Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError = unknown>(eventId: unknown,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStageControllerFindMatchesByStageQueryKey(eventId,stageId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>> = ({ signal }) => stageControllerFindMatchesByStage(eventId,stageId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId && stageId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StageControllerFindMatchesByStageQueryResult = NonNullable<Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>>
export type StageControllerFindMatchesByStageQueryError = unknown


export function useStageControllerFindMatchesByStage<TData = Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError = unknown>(
 eventId: unknown,
    stageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>,
          TError,
          Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStageControllerFindMatchesByStage<TData = Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError = unknown>(
 eventId: unknown,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>,
          TError,
          Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStageControllerFindMatchesByStage<TData = Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError = unknown>(
 eventId: unknown,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all matches for a stage
 */

export function useStageControllerFindMatchesByStage<TData = Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError = unknown>(
 eventId: unknown,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stageControllerFindMatchesByStage>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStageControllerFindMatchesByStageQueryOptions(eventId,stageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Generate matches for stage based on tournament type
 */
export type stageControllerGenerateMatchesResponse201 = {
  data: Match[]
  status: 201
}
    
export type stageControllerGenerateMatchesResponseSuccess = (stageControllerGenerateMatchesResponse201) & {
  headers: Headers;
};
;

export type stageControllerGenerateMatchesResponse = (stageControllerGenerateMatchesResponseSuccess)

export const getStageControllerGenerateMatchesUrl = (eventId: unknown,
    stageId: string,) => {


  

  return `/events/${eventId}/stages/${stageId}/generate-matches`
}

export const stageControllerGenerateMatches = async (eventId: unknown,
    stageId: string, options?: RequestInit): Promise<stageControllerGenerateMatchesResponse> => {
  
  return defaultMutator<stageControllerGenerateMatchesResponse>(getStageControllerGenerateMatchesUrl(eventId,stageId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getStageControllerGenerateMatchesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerGenerateMatches>>, TError,{eventId: unknown;stageId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof stageControllerGenerateMatches>>, TError,{eventId: unknown;stageId: string}, TContext> => {

const mutationKey = ['stageControllerGenerateMatches'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stageControllerGenerateMatches>>, {eventId: unknown;stageId: string}> = (props) => {
          const {eventId,stageId} = props ?? {};

          return  stageControllerGenerateMatches(eventId,stageId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StageControllerGenerateMatchesMutationResult = NonNullable<Awaited<ReturnType<typeof stageControllerGenerateMatches>>>
    
    export type StageControllerGenerateMatchesMutationError = unknown

    /**
 * @summary Generate matches for stage based on tournament type
 */
export const useStageControllerGenerateMatches = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerGenerateMatches>>, TError,{eventId: unknown;stageId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stageControllerGenerateMatches>>,
        TError,
        {eventId: unknown;stageId: string},
        TContext
      > => {
      return useMutation(getStageControllerGenerateMatchesMutationOptions(options), queryClient);
    }
    /**
 * @summary Advance winners to next round/stage
 */
export type stageControllerAdvanceWinnersResponse201 = {
  data: Match[]
  status: 201
}
    
export type stageControllerAdvanceWinnersResponseSuccess = (stageControllerAdvanceWinnersResponse201) & {
  headers: Headers;
};
;

export type stageControllerAdvanceWinnersResponse = (stageControllerAdvanceWinnersResponseSuccess)

export const getStageControllerAdvanceWinnersUrl = (eventId: unknown,
    stageId: string,) => {


  

  return `/events/${eventId}/stages/${stageId}/advance-winners`
}

export const stageControllerAdvanceWinners = async (eventId: unknown,
    stageId: string, options?: RequestInit): Promise<stageControllerAdvanceWinnersResponse> => {
  
  return defaultMutator<stageControllerAdvanceWinnersResponse>(getStageControllerAdvanceWinnersUrl(eventId,stageId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getStageControllerAdvanceWinnersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerAdvanceWinners>>, TError,{eventId: unknown;stageId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof stageControllerAdvanceWinners>>, TError,{eventId: unknown;stageId: string}, TContext> => {

const mutationKey = ['stageControllerAdvanceWinners'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stageControllerAdvanceWinners>>, {eventId: unknown;stageId: string}> = (props) => {
          const {eventId,stageId} = props ?? {};

          return  stageControllerAdvanceWinners(eventId,stageId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StageControllerAdvanceWinnersMutationResult = NonNullable<Awaited<ReturnType<typeof stageControllerAdvanceWinners>>>
    
    export type StageControllerAdvanceWinnersMutationError = unknown

    /**
 * @summary Advance winners to next round/stage
 */
export const useStageControllerAdvanceWinners = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stageControllerAdvanceWinners>>, TError,{eventId: unknown;stageId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stageControllerAdvanceWinners>>,
        TError,
        {eventId: unknown;stageId: string},
        TContext
      > => {
      return useMutation(getStageControllerAdvanceWinnersMutationOptions(options), queryClient);
    }
    