/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignMatchDto,
  DispatchControllerAutoAssignParams,
  DispatchControllerGetQueueParams,
  Match,
  SwapCourtDto,
  UnassignMatchDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get match queue (pending matches)
 */
export type dispatchControllerGetQueueResponse200 = {
  data: void
  status: 200
}
    
export type dispatchControllerGetQueueResponseSuccess = (dispatchControllerGetQueueResponse200) & {
  headers: Headers;
};
;

export type dispatchControllerGetQueueResponse = (dispatchControllerGetQueueResponseSuccess)

export const getDispatchControllerGetQueueUrl = (eventId: string,
    params?: DispatchControllerGetQueueParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/events/${eventId}/dispatch/queue?${stringifiedParams}` : `/events/${eventId}/dispatch/queue`
}

export const dispatchControllerGetQueue = async (eventId: string,
    params?: DispatchControllerGetQueueParams, options?: RequestInit): Promise<dispatchControllerGetQueueResponse> => {
  
  return defaultMutator<dispatchControllerGetQueueResponse>(getDispatchControllerGetQueueUrl(eventId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getDispatchControllerGetQueueQueryKey = (eventId: string,
    params?: DispatchControllerGetQueueParams,) => {
    return [
    `/events/${eventId}/dispatch/queue`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getDispatchControllerGetQueueQueryOptions = <TData = Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError = unknown>(eventId: string,
    params?: DispatchControllerGetQueueParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDispatchControllerGetQueueQueryKey(eventId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dispatchControllerGetQueue>>> = ({ signal }) => dispatchControllerGetQueue(eventId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DispatchControllerGetQueueQueryResult = NonNullable<Awaited<ReturnType<typeof dispatchControllerGetQueue>>>
export type DispatchControllerGetQueueQueryError = unknown


export function useDispatchControllerGetQueue<TData = Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError = unknown>(
 eventId: string,
    params: undefined |  DispatchControllerGetQueueParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dispatchControllerGetQueue>>,
          TError,
          Awaited<ReturnType<typeof dispatchControllerGetQueue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDispatchControllerGetQueue<TData = Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError = unknown>(
 eventId: string,
    params?: DispatchControllerGetQueueParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dispatchControllerGetQueue>>,
          TError,
          Awaited<ReturnType<typeof dispatchControllerGetQueue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDispatchControllerGetQueue<TData = Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError = unknown>(
 eventId: string,
    params?: DispatchControllerGetQueueParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get match queue (pending matches)
 */

export function useDispatchControllerGetQueue<TData = Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError = unknown>(
 eventId: string,
    params?: DispatchControllerGetQueueParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dispatchControllerGetQueue>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDispatchControllerGetQueueQueryOptions(eventId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Assign match to court
 */
export type dispatchControllerAssignResponse200 = {
  data: Match
  status: 200
}
    
export type dispatchControllerAssignResponseSuccess = (dispatchControllerAssignResponse200) & {
  headers: Headers;
};
;

export type dispatchControllerAssignResponse = (dispatchControllerAssignResponseSuccess)

export const getDispatchControllerAssignUrl = (eventId: unknown,) => {


  

  return `/events/${eventId}/dispatch/assign`
}

export const dispatchControllerAssign = async (eventId: unknown,
    assignMatchDto: AssignMatchDto, options?: RequestInit): Promise<dispatchControllerAssignResponse> => {
  
  return defaultMutator<dispatchControllerAssignResponse>(getDispatchControllerAssignUrl(eventId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignMatchDto,)
  }
);}




export const getDispatchControllerAssignMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerAssign>>, TError,{eventId: unknown;data: AssignMatchDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerAssign>>, TError,{eventId: unknown;data: AssignMatchDto}, TContext> => {

const mutationKey = ['dispatchControllerAssign'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dispatchControllerAssign>>, {eventId: unknown;data: AssignMatchDto}> = (props) => {
          const {eventId,data} = props ?? {};

          return  dispatchControllerAssign(eventId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DispatchControllerAssignMutationResult = NonNullable<Awaited<ReturnType<typeof dispatchControllerAssign>>>
    export type DispatchControllerAssignMutationBody = AssignMatchDto
    export type DispatchControllerAssignMutationError = unknown

    /**
 * @summary Assign match to court
 */
export const useDispatchControllerAssign = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerAssign>>, TError,{eventId: unknown;data: AssignMatchDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dispatchControllerAssign>>,
        TError,
        {eventId: unknown;data: AssignMatchDto},
        TContext
      > => {
      return useMutation(getDispatchControllerAssignMutationOptions(options), queryClient);
    }
    /**
 * @summary Unassign match from court
 */
export type dispatchControllerUnassignResponse200 = {
  data: Match
  status: 200
}
    
export type dispatchControllerUnassignResponseSuccess = (dispatchControllerUnassignResponse200) & {
  headers: Headers;
};
;

export type dispatchControllerUnassignResponse = (dispatchControllerUnassignResponseSuccess)

export const getDispatchControllerUnassignUrl = (eventId: unknown,) => {


  

  return `/events/${eventId}/dispatch/unassign`
}

export const dispatchControllerUnassign = async (eventId: unknown,
    unassignMatchDto: UnassignMatchDto, options?: RequestInit): Promise<dispatchControllerUnassignResponse> => {
  
  return defaultMutator<dispatchControllerUnassignResponse>(getDispatchControllerUnassignUrl(eventId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      unassignMatchDto,)
  }
);}




export const getDispatchControllerUnassignMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerUnassign>>, TError,{eventId: unknown;data: UnassignMatchDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerUnassign>>, TError,{eventId: unknown;data: UnassignMatchDto}, TContext> => {

const mutationKey = ['dispatchControllerUnassign'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dispatchControllerUnassign>>, {eventId: unknown;data: UnassignMatchDto}> = (props) => {
          const {eventId,data} = props ?? {};

          return  dispatchControllerUnassign(eventId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DispatchControllerUnassignMutationResult = NonNullable<Awaited<ReturnType<typeof dispatchControllerUnassign>>>
    export type DispatchControllerUnassignMutationBody = UnassignMatchDto
    export type DispatchControllerUnassignMutationError = unknown

    /**
 * @summary Unassign match from court
 */
export const useDispatchControllerUnassign = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerUnassign>>, TError,{eventId: unknown;data: UnassignMatchDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dispatchControllerUnassign>>,
        TError,
        {eventId: unknown;data: UnassignMatchDto},
        TContext
      > => {
      return useMutation(getDispatchControllerUnassignMutationOptions(options), queryClient);
    }
    /**
 * @summary Auto-assign pending matches to available courts
 */
export type dispatchControllerAutoAssignResponse200 = {
  data: void
  status: 200
}
    
export type dispatchControllerAutoAssignResponseSuccess = (dispatchControllerAutoAssignResponse200) & {
  headers: Headers;
};
;

export type dispatchControllerAutoAssignResponse = (dispatchControllerAutoAssignResponseSuccess)

export const getDispatchControllerAutoAssignUrl = (eventId: string,
    params?: DispatchControllerAutoAssignParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/events/${eventId}/dispatch/auto-assign?${stringifiedParams}` : `/events/${eventId}/dispatch/auto-assign`
}

export const dispatchControllerAutoAssign = async (eventId: string,
    params?: DispatchControllerAutoAssignParams, options?: RequestInit): Promise<dispatchControllerAutoAssignResponse> => {
  
  return defaultMutator<dispatchControllerAutoAssignResponse>(getDispatchControllerAutoAssignUrl(eventId,params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getDispatchControllerAutoAssignMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerAutoAssign>>, TError,{eventId: string;params?: DispatchControllerAutoAssignParams}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerAutoAssign>>, TError,{eventId: string;params?: DispatchControllerAutoAssignParams}, TContext> => {

const mutationKey = ['dispatchControllerAutoAssign'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dispatchControllerAutoAssign>>, {eventId: string;params?: DispatchControllerAutoAssignParams}> = (props) => {
          const {eventId,params} = props ?? {};

          return  dispatchControllerAutoAssign(eventId,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DispatchControllerAutoAssignMutationResult = NonNullable<Awaited<ReturnType<typeof dispatchControllerAutoAssign>>>
    
    export type DispatchControllerAutoAssignMutationError = unknown

    /**
 * @summary Auto-assign pending matches to available courts
 */
export const useDispatchControllerAutoAssign = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerAutoAssign>>, TError,{eventId: string;params?: DispatchControllerAutoAssignParams}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dispatchControllerAutoAssign>>,
        TError,
        {eventId: string;params?: DispatchControllerAutoAssignParams},
        TContext
      > => {
      return useMutation(getDispatchControllerAutoAssignMutationOptions(options), queryClient);
    }
    /**
 * @summary Swap court for an active match
 */
export type dispatchControllerSwapCourtResponse200 = {
  data: Match
  status: 200
}
    
export type dispatchControllerSwapCourtResponseSuccess = (dispatchControllerSwapCourtResponse200) & {
  headers: Headers;
};
;

export type dispatchControllerSwapCourtResponse = (dispatchControllerSwapCourtResponseSuccess)

export const getDispatchControllerSwapCourtUrl = (eventId: unknown,) => {


  

  return `/events/${eventId}/dispatch/swap-court`
}

export const dispatchControllerSwapCourt = async (eventId: unknown,
    swapCourtDto: SwapCourtDto, options?: RequestInit): Promise<dispatchControllerSwapCourtResponse> => {
  
  return defaultMutator<dispatchControllerSwapCourtResponse>(getDispatchControllerSwapCourtUrl(eventId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      swapCourtDto,)
  }
);}




export const getDispatchControllerSwapCourtMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerSwapCourt>>, TError,{eventId: unknown;data: SwapCourtDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerSwapCourt>>, TError,{eventId: unknown;data: SwapCourtDto}, TContext> => {

const mutationKey = ['dispatchControllerSwapCourt'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dispatchControllerSwapCourt>>, {eventId: unknown;data: SwapCourtDto}> = (props) => {
          const {eventId,data} = props ?? {};

          return  dispatchControllerSwapCourt(eventId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DispatchControllerSwapCourtMutationResult = NonNullable<Awaited<ReturnType<typeof dispatchControllerSwapCourt>>>
    export type DispatchControllerSwapCourtMutationBody = SwapCourtDto
    export type DispatchControllerSwapCourtMutationError = unknown

    /**
 * @summary Swap court for an active match
 */
export const useDispatchControllerSwapCourt = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchControllerSwapCourt>>, TError,{eventId: unknown;data: SwapCourtDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dispatchControllerSwapCourt>>,
        TError,
        {eventId: unknown;data: SwapCourtDto},
        TContext
      > => {
      return useMutation(getDispatchControllerSwapCourtMutationOptions(options), queryClient);
    }
    