/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ValidateQrDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Validate court QR token and issue court access JWT
 */
export type courtAccessControllerValidateQrResponse200 = {
  data: void
  status: 200
}

export type courtAccessControllerValidateQrResponse400 = {
  data: void
  status: 400
}
    
export type courtAccessControllerValidateQrResponseSuccess = (courtAccessControllerValidateQrResponse200) & {
  headers: Headers;
};
export type courtAccessControllerValidateQrResponseError = (courtAccessControllerValidateQrResponse400) & {
  headers: Headers;
};

export type courtAccessControllerValidateQrResponse = (courtAccessControllerValidateQrResponseSuccess | courtAccessControllerValidateQrResponseError)

export const getCourtAccessControllerValidateQrUrl = () => {


  

  return `/auth/court/qr`
}

export const courtAccessControllerValidateQr = async (validateQrDto: ValidateQrDto, options?: RequestInit): Promise<courtAccessControllerValidateQrResponse> => {
  
  return defaultMutator<courtAccessControllerValidateQrResponse>(getCourtAccessControllerValidateQrUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      validateQrDto,)
  }
);}




export const getCourtAccessControllerValidateQrMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courtAccessControllerValidateQr>>, TError,{data: ValidateQrDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof courtAccessControllerValidateQr>>, TError,{data: ValidateQrDto}, TContext> => {

const mutationKey = ['courtAccessControllerValidateQr'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof courtAccessControllerValidateQr>>, {data: ValidateQrDto}> = (props) => {
          const {data} = props ?? {};

          return  courtAccessControllerValidateQr(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CourtAccessControllerValidateQrMutationResult = NonNullable<Awaited<ReturnType<typeof courtAccessControllerValidateQr>>>
    export type CourtAccessControllerValidateQrMutationBody = ValidateQrDto
    export type CourtAccessControllerValidateQrMutationError = void

    /**
 * @summary Validate court QR token and issue court access JWT
 */
export const useCourtAccessControllerValidateQr = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof courtAccessControllerValidateQr>>, TError,{data: ValidateQrDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof courtAccessControllerValidateQr>>,
        TError,
        {data: ValidateQrDto},
        TContext
      > => {
      return useMutation(getCourtAccessControllerValidateQrMutationOptions(options), queryClient);
    }
    