/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InitSepayPaymentDto,
  OrderPublicResponseDto,
  SepayIpnPayloadDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Initialize SePay payment for a campaign order
 */
export type campaignOrderSepayControllerInitPaymentResponse200 = {
  data: void
  status: 200
}
    
export type campaignOrderSepayControllerInitPaymentResponseSuccess = (campaignOrderSepayControllerInitPaymentResponse200) & {
  headers: Headers;
};
;

export type campaignOrderSepayControllerInitPaymentResponse = (campaignOrderSepayControllerInitPaymentResponseSuccess)

export const getCampaignOrderSepayControllerInitPaymentUrl = (campaignId: string,
    orderCode: string,) => {


  

  return `/campaigns/${campaignId}/orders/${orderCode}/sepay/init`
}

export const campaignOrderSepayControllerInitPayment = async (campaignId: string,
    orderCode: string,
    initSepayPaymentDto: InitSepayPaymentDto, options?: RequestInit): Promise<campaignOrderSepayControllerInitPaymentResponse> => {
  
  return defaultMutator<campaignOrderSepayControllerInitPaymentResponse>(getCampaignOrderSepayControllerInitPaymentUrl(campaignId,orderCode),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      initSepayPaymentDto,)
  }
);}




export const getCampaignOrderSepayControllerInitPaymentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>, TError,{campaignId: string;orderCode: string;data: InitSepayPaymentDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>, TError,{campaignId: string;orderCode: string;data: InitSepayPaymentDto}, TContext> => {

const mutationKey = ['campaignOrderSepayControllerInitPayment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>, {campaignId: string;orderCode: string;data: InitSepayPaymentDto}> = (props) => {
          const {campaignId,orderCode,data} = props ?? {};

          return  campaignOrderSepayControllerInitPayment(campaignId,orderCode,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignOrderSepayControllerInitPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>>
    export type CampaignOrderSepayControllerInitPaymentMutationBody = InitSepayPaymentDto
    export type CampaignOrderSepayControllerInitPaymentMutationError = unknown

    /**
 * @summary Initialize SePay payment for a campaign order
 */
export const useCampaignOrderSepayControllerInitPayment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>, TError,{campaignId: string;orderCode: string;data: InitSepayPaymentDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>,
        TError,
        {campaignId: string;orderCode: string;data: InitSepayPaymentDto},
        TContext
      > => {
      return useMutation(getCampaignOrderSepayControllerInitPaymentMutationOptions(options), queryClient);
    }
    /**
 * @summary Get public order summary (no auth required)
 */
export type campaignOrderSepayControllerFindOnePublicResponse200 = {
  data: OrderPublicResponseDto
  status: 200
}
    
export type campaignOrderSepayControllerFindOnePublicResponseSuccess = (campaignOrderSepayControllerFindOnePublicResponse200) & {
  headers: Headers;
};
;

export type campaignOrderSepayControllerFindOnePublicResponse = (campaignOrderSepayControllerFindOnePublicResponseSuccess)

export const getCampaignOrderSepayControllerFindOnePublicUrl = (orderCode: string,) => {


  

  return `/orders/${orderCode}/public`
}

export const campaignOrderSepayControllerFindOnePublic = async (orderCode: string, options?: RequestInit): Promise<campaignOrderSepayControllerFindOnePublicResponse> => {
  
  return defaultMutator<campaignOrderSepayControllerFindOnePublicResponse>(getCampaignOrderSepayControllerFindOnePublicUrl(orderCode),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignOrderSepayControllerFindOnePublicQueryKey = (orderCode: string,) => {
    return [
    `/orders/${orderCode}/public`
    ] as const;
    }

    
export const getCampaignOrderSepayControllerFindOnePublicQueryOptions = <TData = Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError = unknown>(orderCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignOrderSepayControllerFindOnePublicQueryKey(orderCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>> = ({ signal }) => campaignOrderSepayControllerFindOnePublic(orderCode, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orderCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignOrderSepayControllerFindOnePublicQueryResult = NonNullable<Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>>
export type CampaignOrderSepayControllerFindOnePublicQueryError = unknown


export function useCampaignOrderSepayControllerFindOnePublic<TData = Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError = unknown>(
 orderCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>,
          TError,
          Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignOrderSepayControllerFindOnePublic<TData = Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError = unknown>(
 orderCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>,
          TError,
          Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignOrderSepayControllerFindOnePublic<TData = Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError = unknown>(
 orderCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get public order summary (no auth required)
 */

export function useCampaignOrderSepayControllerFindOnePublic<TData = Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError = unknown>(
 orderCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerFindOnePublic>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignOrderSepayControllerFindOnePublicQueryOptions(orderCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary SePay IPN webhook — receives payment confirmation from SePay
 */
export type campaignOrderSepayControllerProcessIpnResponse200 = {
  data: void
  status: 200
}
    
export type campaignOrderSepayControllerProcessIpnResponseSuccess = (campaignOrderSepayControllerProcessIpnResponse200) & {
  headers: Headers;
};
;

export type campaignOrderSepayControllerProcessIpnResponse = (campaignOrderSepayControllerProcessIpnResponseSuccess)

export const getCampaignOrderSepayControllerProcessIpnUrl = () => {


  

  return `/campaigns/orders/sepay/ipn`
}

export const campaignOrderSepayControllerProcessIpn = async (sepayIpnPayloadDto: SepayIpnPayloadDto, options?: RequestInit): Promise<campaignOrderSepayControllerProcessIpnResponse> => {
  
  return defaultMutator<campaignOrderSepayControllerProcessIpnResponse>(getCampaignOrderSepayControllerProcessIpnUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sepayIpnPayloadDto,)
  }
);}




export const getCampaignOrderSepayControllerProcessIpnMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>, TError,{data: SepayIpnPayloadDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>, TError,{data: SepayIpnPayloadDto}, TContext> => {

const mutationKey = ['campaignOrderSepayControllerProcessIpn'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>, {data: SepayIpnPayloadDto}> = (props) => {
          const {data} = props ?? {};

          return  campaignOrderSepayControllerProcessIpn(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignOrderSepayControllerProcessIpnMutationResult = NonNullable<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>>
    export type CampaignOrderSepayControllerProcessIpnMutationBody = SepayIpnPayloadDto
    export type CampaignOrderSepayControllerProcessIpnMutationError = unknown

    /**
 * @summary SePay IPN webhook — receives payment confirmation from SePay
 */
export const useCampaignOrderSepayControllerProcessIpn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>, TError,{data: SepayIpnPayloadDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>,
        TError,
        {data: SepayIpnPayloadDto},
        TContext
      > => {
      return useMutation(getCampaignOrderSepayControllerProcessIpnMutationOptions(options), queryClient);
    }
    