/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePaymentDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type paymentsControllerCreatePaymentUrlResponse201 = {
  data: void
  status: 201
}
    
export type paymentsControllerCreatePaymentUrlResponseSuccess = (paymentsControllerCreatePaymentUrlResponse201) & {
  headers: Headers;
};
;

export type paymentsControllerCreatePaymentUrlResponse = (paymentsControllerCreatePaymentUrlResponseSuccess)

export const getPaymentsControllerCreatePaymentUrlUrl = () => {


  

  return `/payments/create-url`
}

export const paymentsControllerCreatePaymentUrl = async (createPaymentDto: CreatePaymentDto, options?: RequestInit): Promise<paymentsControllerCreatePaymentUrlResponse> => {
  
  return defaultMutator<paymentsControllerCreatePaymentUrlResponse>(getPaymentsControllerCreatePaymentUrlUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPaymentDto,)
  }
);}




export const getPaymentsControllerCreatePaymentUrlMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentsControllerCreatePaymentUrl>>, TError,{data: CreatePaymentDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentsControllerCreatePaymentUrl>>, TError,{data: CreatePaymentDto}, TContext> => {

const mutationKey = ['paymentsControllerCreatePaymentUrl'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentsControllerCreatePaymentUrl>>, {data: CreatePaymentDto}> = (props) => {
          const {data} = props ?? {};

          return  paymentsControllerCreatePaymentUrl(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PaymentsControllerCreatePaymentUrlMutationResult = NonNullable<Awaited<ReturnType<typeof paymentsControllerCreatePaymentUrl>>>
    export type PaymentsControllerCreatePaymentUrlMutationBody = CreatePaymentDto
    export type PaymentsControllerCreatePaymentUrlMutationError = unknown

    export const usePaymentsControllerCreatePaymentUrl = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentsControllerCreatePaymentUrl>>, TError,{data: CreatePaymentDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentsControllerCreatePaymentUrl>>,
        TError,
        {data: CreatePaymentDto},
        TContext
      > => {
      return useMutation(getPaymentsControllerCreatePaymentUrlMutationOptions(options), queryClient);
    }
    export type paymentsControllerInquirePaymentResponse200 = {
  data: void
  status: 200
}
    
export type paymentsControllerInquirePaymentResponseSuccess = (paymentsControllerInquirePaymentResponse200) & {
  headers: Headers;
};
;

export type paymentsControllerInquirePaymentResponse = (paymentsControllerInquirePaymentResponseSuccess)

export const getPaymentsControllerInquirePaymentUrl = (orderId: string,) => {


  

  return `/payments/inquiry/${orderId}`
}

export const paymentsControllerInquirePayment = async (orderId: string, options?: RequestInit): Promise<paymentsControllerInquirePaymentResponse> => {
  
  return defaultMutator<paymentsControllerInquirePaymentResponse>(getPaymentsControllerInquirePaymentUrl(orderId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPaymentsControllerInquirePaymentQueryKey = (orderId: string,) => {
    return [
    `/payments/inquiry/${orderId}`
    ] as const;
    }

    
export const getPaymentsControllerInquirePaymentQueryOptions = <TData = Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError = unknown>(orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentsControllerInquirePaymentQueryKey(orderId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentsControllerInquirePayment>>> = ({ signal }) => paymentsControllerInquirePayment(orderId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentsControllerInquirePaymentQueryResult = NonNullable<Awaited<ReturnType<typeof paymentsControllerInquirePayment>>>
export type PaymentsControllerInquirePaymentQueryError = unknown


export function usePaymentsControllerInquirePayment<TData = Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError = unknown>(
 orderId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerInquirePayment>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerInquirePayment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerInquirePayment<TData = Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError = unknown>(
 orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerInquirePayment>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerInquirePayment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerInquirePayment<TData = Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError = unknown>(
 orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePaymentsControllerInquirePayment<TData = Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError = unknown>(
 orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerInquirePayment>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentsControllerInquirePaymentQueryOptions(orderId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type paymentsControllerGetPaymentStatusResponse200 = {
  data: void
  status: 200
}
    
export type paymentsControllerGetPaymentStatusResponseSuccess = (paymentsControllerGetPaymentStatusResponse200) & {
  headers: Headers;
};
;

export type paymentsControllerGetPaymentStatusResponse = (paymentsControllerGetPaymentStatusResponseSuccess)

export const getPaymentsControllerGetPaymentStatusUrl = (orderId: string,) => {


  

  return `/payments/status/${orderId}`
}

export const paymentsControllerGetPaymentStatus = async (orderId: string, options?: RequestInit): Promise<paymentsControllerGetPaymentStatusResponse> => {
  
  return defaultMutator<paymentsControllerGetPaymentStatusResponse>(getPaymentsControllerGetPaymentStatusUrl(orderId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPaymentsControllerGetPaymentStatusQueryKey = (orderId: string,) => {
    return [
    `/payments/status/${orderId}`
    ] as const;
    }

    
export const getPaymentsControllerGetPaymentStatusQueryOptions = <TData = Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError = unknown>(orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentsControllerGetPaymentStatusQueryKey(orderId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>> = ({ signal }) => paymentsControllerGetPaymentStatus(orderId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentsControllerGetPaymentStatusQueryResult = NonNullable<Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>>
export type PaymentsControllerGetPaymentStatusQueryError = unknown


export function usePaymentsControllerGetPaymentStatus<TData = Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError = unknown>(
 orderId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerGetPaymentStatus<TData = Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError = unknown>(
 orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerGetPaymentStatus<TData = Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError = unknown>(
 orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePaymentsControllerGetPaymentStatus<TData = Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError = unknown>(
 orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerGetPaymentStatus>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentsControllerGetPaymentStatusQueryOptions(orderId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type paymentsControllerVerifyReturnLegacyResponse200 = {
  data: void
  status: 200
}
    
export type paymentsControllerVerifyReturnLegacyResponseSuccess = (paymentsControllerVerifyReturnLegacyResponse200) & {
  headers: Headers;
};
;

export type paymentsControllerVerifyReturnLegacyResponse = (paymentsControllerVerifyReturnLegacyResponseSuccess)

export const getPaymentsControllerVerifyReturnLegacyUrl = () => {


  

  return `/payments/return`
}

export const paymentsControllerVerifyReturnLegacy = async ( options?: RequestInit): Promise<paymentsControllerVerifyReturnLegacyResponse> => {
  
  return defaultMutator<paymentsControllerVerifyReturnLegacyResponse>(getPaymentsControllerVerifyReturnLegacyUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPaymentsControllerVerifyReturnLegacyQueryKey = () => {
    return [
    `/payments/return`
    ] as const;
    }

    
export const getPaymentsControllerVerifyReturnLegacyQueryOptions = <TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentsControllerVerifyReturnLegacyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>> = ({ signal }) => paymentsControllerVerifyReturnLegacy({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentsControllerVerifyReturnLegacyQueryResult = NonNullable<Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>>
export type PaymentsControllerVerifyReturnLegacyQueryError = unknown


export function usePaymentsControllerVerifyReturnLegacy<TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerVerifyReturnLegacy<TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerVerifyReturnLegacy<TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePaymentsControllerVerifyReturnLegacy<TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturnLegacy>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentsControllerVerifyReturnLegacyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type paymentsControllerVerifyReturnResponse200 = {
  data: void
  status: 200
}
    
export type paymentsControllerVerifyReturnResponseSuccess = (paymentsControllerVerifyReturnResponse200) & {
  headers: Headers;
};
;

export type paymentsControllerVerifyReturnResponse = (paymentsControllerVerifyReturnResponseSuccess)

export const getPaymentsControllerVerifyReturnUrl = (paymentMethod: string,) => {


  

  return `/payments/${paymentMethod}/return`
}

export const paymentsControllerVerifyReturn = async (paymentMethod: string, options?: RequestInit): Promise<paymentsControllerVerifyReturnResponse> => {
  
  return defaultMutator<paymentsControllerVerifyReturnResponse>(getPaymentsControllerVerifyReturnUrl(paymentMethod),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPaymentsControllerVerifyReturnQueryKey = (paymentMethod: string,) => {
    return [
    `/payments/${paymentMethod}/return`
    ] as const;
    }

    
export const getPaymentsControllerVerifyReturnQueryOptions = <TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError = unknown>(paymentMethod: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentsControllerVerifyReturnQueryKey(paymentMethod);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>> = ({ signal }) => paymentsControllerVerifyReturn(paymentMethod, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(paymentMethod), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentsControllerVerifyReturnQueryResult = NonNullable<Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>>
export type PaymentsControllerVerifyReturnQueryError = unknown


export function usePaymentsControllerVerifyReturn<TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError = unknown>(
 paymentMethod: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerVerifyReturn<TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError = unknown>(
 paymentMethod: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerVerifyReturn<TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError = unknown>(
 paymentMethod: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePaymentsControllerVerifyReturn<TData = Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError = unknown>(
 paymentMethod: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerVerifyReturn>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentsControllerVerifyReturnQueryOptions(paymentMethod,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type paymentsControllerHandleCallbackResponse201 = {
  data: void
  status: 201
}
    
export type paymentsControllerHandleCallbackResponseSuccess = (paymentsControllerHandleCallbackResponse201) & {
  headers: Headers;
};
;

export type paymentsControllerHandleCallbackResponse = (paymentsControllerHandleCallbackResponseSuccess)

export const getPaymentsControllerHandleCallbackUrl = (paymentMethod: string,) => {


  

  return `/payments/${paymentMethod}/callback`
}

export const paymentsControllerHandleCallback = async (paymentMethod: string, options?: RequestInit): Promise<paymentsControllerHandleCallbackResponse> => {
  
  return defaultMutator<paymentsControllerHandleCallbackResponse>(getPaymentsControllerHandleCallbackUrl(paymentMethod),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getPaymentsControllerHandleCallbackMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentsControllerHandleCallback>>, TError,{paymentMethod: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentsControllerHandleCallback>>, TError,{paymentMethod: string}, TContext> => {

const mutationKey = ['paymentsControllerHandleCallback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentsControllerHandleCallback>>, {paymentMethod: string}> = (props) => {
          const {paymentMethod} = props ?? {};

          return  paymentsControllerHandleCallback(paymentMethod,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PaymentsControllerHandleCallbackMutationResult = NonNullable<Awaited<ReturnType<typeof paymentsControllerHandleCallback>>>
    
    export type PaymentsControllerHandleCallbackMutationError = unknown

    export const usePaymentsControllerHandleCallback = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentsControllerHandleCallback>>, TError,{paymentMethod: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentsControllerHandleCallback>>,
        TError,
        {paymentMethod: string},
        TContext
      > => {
      return useMutation(getPaymentsControllerHandleCallbackMutationOptions(options), queryClient);
    }
    export type paymentsControllerFindOneResponse200 = {
  data: void
  status: 200
}
    
export type paymentsControllerFindOneResponseSuccess = (paymentsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type paymentsControllerFindOneResponse = (paymentsControllerFindOneResponseSuccess)

export const getPaymentsControllerFindOneUrl = (id: string,) => {


  

  return `/payments/${id}`
}

export const paymentsControllerFindOne = async (id: string, options?: RequestInit): Promise<paymentsControllerFindOneResponse> => {
  
  return defaultMutator<paymentsControllerFindOneResponse>(getPaymentsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPaymentsControllerFindOneQueryKey = (id: string,) => {
    return [
    `/payments/${id}`
    ] as const;
    }

    
export const getPaymentsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentsControllerFindOne>>> = ({ signal }) => paymentsControllerFindOne(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof paymentsControllerFindOne>>>
export type PaymentsControllerFindOneQueryError = unknown


export function usePaymentsControllerFindOne<TData = Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerFindOne<TData = Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof paymentsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentsControllerFindOne<TData = Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePaymentsControllerFindOne<TData = Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type paymentsControllerRemoveResponse200 = {
  data: void
  status: 200
}
    
export type paymentsControllerRemoveResponseSuccess = (paymentsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type paymentsControllerRemoveResponse = (paymentsControllerRemoveResponseSuccess)

export const getPaymentsControllerRemoveUrl = (id: string,) => {


  

  return `/payments/${id}`
}

export const paymentsControllerRemove = async (id: string, options?: RequestInit): Promise<paymentsControllerRemoveResponse> => {
  
  return defaultMutator<paymentsControllerRemoveResponse>(getPaymentsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getPaymentsControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentsControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['paymentsControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  paymentsControllerRemove(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PaymentsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof paymentsControllerRemove>>>
    
    export type PaymentsControllerRemoveMutationError = unknown

    export const usePaymentsControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentsControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPaymentsControllerRemoveMutationOptions(options), queryClient);
    }
    