/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CampaignControllerCreate201,
  CampaignControllerFindAll200,
  CampaignControllerFindBySlug200,
  CampaignControllerFindOne200,
  CampaignControllerFindPublic200,
  CampaignControllerFindPublicParams,
  CampaignControllerUpdate200,
  CampaignControllerUpdateStatus200,
  CreateCampaignDto,
  UpdateCampaignDto,
  UpdateCampaignStatusDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type campaignControllerCreateResponse201 = {
  data: CampaignControllerCreate201
  status: 201
}
    
export type campaignControllerCreateResponseSuccess = (campaignControllerCreateResponse201) & {
  headers: Headers;
};
;

export type campaignControllerCreateResponse = (campaignControllerCreateResponseSuccess)

export const getCampaignControllerCreateUrl = () => {


  

  return `/campaigns`
}

export const campaignControllerCreate = async (createCampaignDto: CreateCampaignDto, options?: RequestInit): Promise<campaignControllerCreateResponse> => {
  
  return defaultMutator<campaignControllerCreateResponse>(getCampaignControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCampaignDto,)
  }
);}




export const getCampaignControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignControllerCreate>>, TError,{data: CreateCampaignDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignControllerCreate>>, TError,{data: CreateCampaignDto}, TContext> => {

const mutationKey = ['campaignControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignControllerCreate>>, {data: CreateCampaignDto}> = (props) => {
          const {data} = props ?? {};

          return  campaignControllerCreate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof campaignControllerCreate>>>
    export type CampaignControllerCreateMutationBody = CreateCampaignDto
    export type CampaignControllerCreateMutationError = unknown

    export const useCampaignControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignControllerCreate>>, TError,{data: CreateCampaignDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignControllerCreate>>,
        TError,
        {data: CreateCampaignDto},
        TContext
      > => {
      return useMutation(getCampaignControllerCreateMutationOptions(options), queryClient);
    }
    export type campaignControllerFindAllResponse200 = {
  data: CampaignControllerFindAll200
  status: 200
}
    
export type campaignControllerFindAllResponseSuccess = (campaignControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type campaignControllerFindAllResponse = (campaignControllerFindAllResponseSuccess)

export const getCampaignControllerFindAllUrl = () => {


  

  return `/campaigns`
}

export const campaignControllerFindAll = async ( options?: RequestInit): Promise<campaignControllerFindAllResponse> => {
  
  return defaultMutator<campaignControllerFindAllResponse>(getCampaignControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignControllerFindAllQueryKey = () => {
    return [
    `/campaigns`
    ] as const;
    }

    
export const getCampaignControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof campaignControllerFindAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignControllerFindAll>>> = ({ signal }) => campaignControllerFindAll({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof campaignControllerFindAll>>>
export type CampaignControllerFindAllQueryError = unknown


export function useCampaignControllerFindAll<TData = Awaited<ReturnType<typeof campaignControllerFindAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof campaignControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignControllerFindAll<TData = Awaited<ReturnType<typeof campaignControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof campaignControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignControllerFindAll<TData = Awaited<ReturnType<typeof campaignControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCampaignControllerFindAll<TData = Awaited<ReturnType<typeof campaignControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type campaignControllerFindPublicResponse200 = {
  data: CampaignControllerFindPublic200
  status: 200
}
    
export type campaignControllerFindPublicResponseSuccess = (campaignControllerFindPublicResponse200) & {
  headers: Headers;
};
;

export type campaignControllerFindPublicResponse = (campaignControllerFindPublicResponseSuccess)

export const getCampaignControllerFindPublicUrl = (params?: CampaignControllerFindPublicParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/campaigns/public?${stringifiedParams}` : `/campaigns/public`
}

export const campaignControllerFindPublic = async (params?: CampaignControllerFindPublicParams, options?: RequestInit): Promise<campaignControllerFindPublicResponse> => {
  
  return defaultMutator<campaignControllerFindPublicResponse>(getCampaignControllerFindPublicUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignControllerFindPublicQueryKey = (params?: CampaignControllerFindPublicParams,) => {
    return [
    `/campaigns/public`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getCampaignControllerFindPublicQueryOptions = <TData = Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError = unknown>(params?: CampaignControllerFindPublicParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignControllerFindPublicQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignControllerFindPublic>>> = ({ signal }) => campaignControllerFindPublic(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignControllerFindPublicQueryResult = NonNullable<Awaited<ReturnType<typeof campaignControllerFindPublic>>>
export type CampaignControllerFindPublicQueryError = unknown


export function useCampaignControllerFindPublic<TData = Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError = unknown>(
 params: undefined |  CampaignControllerFindPublicParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignControllerFindPublic>>,
          TError,
          Awaited<ReturnType<typeof campaignControllerFindPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignControllerFindPublic<TData = Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError = unknown>(
 params?: CampaignControllerFindPublicParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignControllerFindPublic>>,
          TError,
          Awaited<ReturnType<typeof campaignControllerFindPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignControllerFindPublic<TData = Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError = unknown>(
 params?: CampaignControllerFindPublicParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCampaignControllerFindPublic<TData = Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError = unknown>(
 params?: CampaignControllerFindPublicParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindPublic>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignControllerFindPublicQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type campaignControllerFindBySlugResponse200 = {
  data: CampaignControllerFindBySlug200
  status: 200
}
    
export type campaignControllerFindBySlugResponseSuccess = (campaignControllerFindBySlugResponse200) & {
  headers: Headers;
};
;

export type campaignControllerFindBySlugResponse = (campaignControllerFindBySlugResponseSuccess)

export const getCampaignControllerFindBySlugUrl = (slug: string,) => {


  

  return `/campaigns/public/${slug}`
}

export const campaignControllerFindBySlug = async (slug: string, options?: RequestInit): Promise<campaignControllerFindBySlugResponse> => {
  
  return defaultMutator<campaignControllerFindBySlugResponse>(getCampaignControllerFindBySlugUrl(slug),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignControllerFindBySlugQueryKey = (slug: string,) => {
    return [
    `/campaigns/public/${slug}`
    ] as const;
    }

    
export const getCampaignControllerFindBySlugQueryOptions = <TData = Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError = unknown>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignControllerFindBySlugQueryKey(slug);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignControllerFindBySlug>>> = ({ signal }) => campaignControllerFindBySlug(slug, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignControllerFindBySlugQueryResult = NonNullable<Awaited<ReturnType<typeof campaignControllerFindBySlug>>>
export type CampaignControllerFindBySlugQueryError = unknown


export function useCampaignControllerFindBySlug<TData = Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError = unknown>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignControllerFindBySlug>>,
          TError,
          Awaited<ReturnType<typeof campaignControllerFindBySlug>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignControllerFindBySlug<TData = Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignControllerFindBySlug>>,
          TError,
          Awaited<ReturnType<typeof campaignControllerFindBySlug>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignControllerFindBySlug<TData = Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCampaignControllerFindBySlug<TData = Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindBySlug>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignControllerFindBySlugQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type campaignControllerFindOneResponse200 = {
  data: CampaignControllerFindOne200
  status: 200
}
    
export type campaignControllerFindOneResponseSuccess = (campaignControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type campaignControllerFindOneResponse = (campaignControllerFindOneResponseSuccess)

export const getCampaignControllerFindOneUrl = (id: string,) => {


  

  return `/campaigns/${id}`
}

export const campaignControllerFindOne = async (id: string, options?: RequestInit): Promise<campaignControllerFindOneResponse> => {
  
  return defaultMutator<campaignControllerFindOneResponse>(getCampaignControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignControllerFindOneQueryKey = (id: string,) => {
    return [
    `/campaigns/${id}`
    ] as const;
    }

    
export const getCampaignControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof campaignControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignControllerFindOne>>> = ({ signal }) => campaignControllerFindOne(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof campaignControllerFindOne>>>
export type CampaignControllerFindOneQueryError = unknown


export function useCampaignControllerFindOne<TData = Awaited<ReturnType<typeof campaignControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof campaignControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignControllerFindOne<TData = Awaited<ReturnType<typeof campaignControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof campaignControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignControllerFindOne<TData = Awaited<ReturnType<typeof campaignControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCampaignControllerFindOne<TData = Awaited<ReturnType<typeof campaignControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type campaignControllerUpdateResponse200 = {
  data: CampaignControllerUpdate200
  status: 200
}
    
export type campaignControllerUpdateResponseSuccess = (campaignControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type campaignControllerUpdateResponse = (campaignControllerUpdateResponseSuccess)

export const getCampaignControllerUpdateUrl = (id: string,) => {


  

  return `/campaigns/${id}`
}

export const campaignControllerUpdate = async (id: string,
    updateCampaignDto: UpdateCampaignDto, options?: RequestInit): Promise<campaignControllerUpdateResponse> => {
  
  return defaultMutator<campaignControllerUpdateResponse>(getCampaignControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCampaignDto,)
  }
);}




export const getCampaignControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignControllerUpdate>>, TError,{id: string;data: UpdateCampaignDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignControllerUpdate>>, TError,{id: string;data: UpdateCampaignDto}, TContext> => {

const mutationKey = ['campaignControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignControllerUpdate>>, {id: string;data: UpdateCampaignDto}> = (props) => {
          const {id,data} = props ?? {};

          return  campaignControllerUpdate(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof campaignControllerUpdate>>>
    export type CampaignControllerUpdateMutationBody = UpdateCampaignDto
    export type CampaignControllerUpdateMutationError = unknown

    export const useCampaignControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignControllerUpdate>>, TError,{id: string;data: UpdateCampaignDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignControllerUpdate>>,
        TError,
        {id: string;data: UpdateCampaignDto},
        TContext
      > => {
      return useMutation(getCampaignControllerUpdateMutationOptions(options), queryClient);
    }
    export type campaignControllerRemoveResponse204 = {
  data: void
  status: 204
}
    
export type campaignControllerRemoveResponseSuccess = (campaignControllerRemoveResponse204) & {
  headers: Headers;
};
;

export type campaignControllerRemoveResponse = (campaignControllerRemoveResponseSuccess)

export const getCampaignControllerRemoveUrl = (id: string,) => {


  

  return `/campaigns/${id}`
}

export const campaignControllerRemove = async (id: string, options?: RequestInit): Promise<campaignControllerRemoveResponse> => {
  
  return defaultMutator<campaignControllerRemoveResponse>(getCampaignControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getCampaignControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['campaignControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  campaignControllerRemove(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof campaignControllerRemove>>>
    
    export type CampaignControllerRemoveMutationError = unknown

    export const useCampaignControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getCampaignControllerRemoveMutationOptions(options), queryClient);
    }
    export type campaignControllerUpdateStatusResponse200 = {
  data: CampaignControllerUpdateStatus200
  status: 200
}
    
export type campaignControllerUpdateStatusResponseSuccess = (campaignControllerUpdateStatusResponse200) & {
  headers: Headers;
};
;

export type campaignControllerUpdateStatusResponse = (campaignControllerUpdateStatusResponseSuccess)

export const getCampaignControllerUpdateStatusUrl = (id: string,) => {


  

  return `/campaigns/${id}/status`
}

export const campaignControllerUpdateStatus = async (id: string,
    updateCampaignStatusDto: UpdateCampaignStatusDto, options?: RequestInit): Promise<campaignControllerUpdateStatusResponse> => {
  
  return defaultMutator<campaignControllerUpdateStatusResponse>(getCampaignControllerUpdateStatusUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCampaignStatusDto,)
  }
);}




export const getCampaignControllerUpdateStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignControllerUpdateStatus>>, TError,{id: string;data: UpdateCampaignStatusDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignControllerUpdateStatus>>, TError,{id: string;data: UpdateCampaignStatusDto}, TContext> => {

const mutationKey = ['campaignControllerUpdateStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignControllerUpdateStatus>>, {id: string;data: UpdateCampaignStatusDto}> = (props) => {
          const {id,data} = props ?? {};

          return  campaignControllerUpdateStatus(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignControllerUpdateStatusMutationResult = NonNullable<Awaited<ReturnType<typeof campaignControllerUpdateStatus>>>
    export type CampaignControllerUpdateStatusMutationBody = UpdateCampaignStatusDto
    export type CampaignControllerUpdateStatusMutationError = unknown

    export const useCampaignControllerUpdateStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignControllerUpdateStatus>>, TError,{id: string;data: UpdateCampaignStatusDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignControllerUpdateStatus>>,
        TError,
        {id: string;data: UpdateCampaignStatusDto},
        TContext
      > => {
      return useMutation(getCampaignControllerUpdateStatusMutationOptions(options), queryClient);
    }
    