/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCampaignProductDto,
  CreatePricingPhaseDto,
  UpdateCampaignProductDto,
  UpdatePricingPhaseDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type campaignProductControllerCreateProductResponse201 = {
  data: void
  status: 201
}
    
export type campaignProductControllerCreateProductResponseSuccess = (campaignProductControllerCreateProductResponse201) & {
  headers: Headers;
};
;

export type campaignProductControllerCreateProductResponse = (campaignProductControllerCreateProductResponseSuccess)

export const getCampaignProductControllerCreateProductUrl = (campaignId: string,) => {


  

  return `/campaigns/${campaignId}/products`
}

export const campaignProductControllerCreateProduct = async (campaignId: string,
    createCampaignProductDto: CreateCampaignProductDto, options?: RequestInit): Promise<campaignProductControllerCreateProductResponse> => {
  
  return defaultMutator<campaignProductControllerCreateProductResponse>(getCampaignProductControllerCreateProductUrl(campaignId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCampaignProductDto,)
  }
);}




export const getCampaignProductControllerCreateProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerCreateProduct>>, TError,{campaignId: string;data: CreateCampaignProductDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerCreateProduct>>, TError,{campaignId: string;data: CreateCampaignProductDto}, TContext> => {

const mutationKey = ['campaignProductControllerCreateProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignProductControllerCreateProduct>>, {campaignId: string;data: CreateCampaignProductDto}> = (props) => {
          const {campaignId,data} = props ?? {};

          return  campaignProductControllerCreateProduct(campaignId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignProductControllerCreateProductMutationResult = NonNullable<Awaited<ReturnType<typeof campaignProductControllerCreateProduct>>>
    export type CampaignProductControllerCreateProductMutationBody = CreateCampaignProductDto
    export type CampaignProductControllerCreateProductMutationError = unknown

    export const useCampaignProductControllerCreateProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerCreateProduct>>, TError,{campaignId: string;data: CreateCampaignProductDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignProductControllerCreateProduct>>,
        TError,
        {campaignId: string;data: CreateCampaignProductDto},
        TContext
      > => {
      return useMutation(getCampaignProductControllerCreateProductMutationOptions(options), queryClient);
    }
    export type campaignProductControllerFindProductsResponse200 = {
  data: void
  status: 200
}
    
export type campaignProductControllerFindProductsResponseSuccess = (campaignProductControllerFindProductsResponse200) & {
  headers: Headers;
};
;

export type campaignProductControllerFindProductsResponse = (campaignProductControllerFindProductsResponseSuccess)

export const getCampaignProductControllerFindProductsUrl = (campaignId: string,) => {


  

  return `/campaigns/${campaignId}/products`
}

export const campaignProductControllerFindProducts = async (campaignId: string, options?: RequestInit): Promise<campaignProductControllerFindProductsResponse> => {
  
  return defaultMutator<campaignProductControllerFindProductsResponse>(getCampaignProductControllerFindProductsUrl(campaignId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignProductControllerFindProductsQueryKey = (campaignId: string,) => {
    return [
    `/campaigns/${campaignId}/products`
    ] as const;
    }

    
export const getCampaignProductControllerFindProductsQueryOptions = <TData = Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError = unknown>(campaignId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignProductControllerFindProductsQueryKey(campaignId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignProductControllerFindProducts>>> = ({ signal }) => campaignProductControllerFindProducts(campaignId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(campaignId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignProductControllerFindProductsQueryResult = NonNullable<Awaited<ReturnType<typeof campaignProductControllerFindProducts>>>
export type CampaignProductControllerFindProductsQueryError = unknown


export function useCampaignProductControllerFindProducts<TData = Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError = unknown>(
 campaignId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignProductControllerFindProducts>>,
          TError,
          Awaited<ReturnType<typeof campaignProductControllerFindProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignProductControllerFindProducts<TData = Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError = unknown>(
 campaignId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignProductControllerFindProducts>>,
          TError,
          Awaited<ReturnType<typeof campaignProductControllerFindProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignProductControllerFindProducts<TData = Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError = unknown>(
 campaignId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCampaignProductControllerFindProducts<TData = Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError = unknown>(
 campaignId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindProducts>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignProductControllerFindProductsQueryOptions(campaignId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type campaignProductControllerUpdateProductResponse200 = {
  data: void
  status: 200
}
    
export type campaignProductControllerUpdateProductResponseSuccess = (campaignProductControllerUpdateProductResponse200) & {
  headers: Headers;
};
;

export type campaignProductControllerUpdateProductResponse = (campaignProductControllerUpdateProductResponseSuccess)

export const getCampaignProductControllerUpdateProductUrl = (campaignId: string,
    id: string,) => {


  

  return `/campaigns/${campaignId}/products/${id}`
}

export const campaignProductControllerUpdateProduct = async (campaignId: string,
    id: string,
    updateCampaignProductDto: UpdateCampaignProductDto, options?: RequestInit): Promise<campaignProductControllerUpdateProductResponse> => {
  
  return defaultMutator<campaignProductControllerUpdateProductResponse>(getCampaignProductControllerUpdateProductUrl(campaignId,id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCampaignProductDto,)
  }
);}




export const getCampaignProductControllerUpdateProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerUpdateProduct>>, TError,{campaignId: string;id: string;data: UpdateCampaignProductDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerUpdateProduct>>, TError,{campaignId: string;id: string;data: UpdateCampaignProductDto}, TContext> => {

const mutationKey = ['campaignProductControllerUpdateProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignProductControllerUpdateProduct>>, {campaignId: string;id: string;data: UpdateCampaignProductDto}> = (props) => {
          const {campaignId,id,data} = props ?? {};

          return  campaignProductControllerUpdateProduct(campaignId,id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignProductControllerUpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof campaignProductControllerUpdateProduct>>>
    export type CampaignProductControllerUpdateProductMutationBody = UpdateCampaignProductDto
    export type CampaignProductControllerUpdateProductMutationError = unknown

    export const useCampaignProductControllerUpdateProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerUpdateProduct>>, TError,{campaignId: string;id: string;data: UpdateCampaignProductDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignProductControllerUpdateProduct>>,
        TError,
        {campaignId: string;id: string;data: UpdateCampaignProductDto},
        TContext
      > => {
      return useMutation(getCampaignProductControllerUpdateProductMutationOptions(options), queryClient);
    }
    export type campaignProductControllerRemoveProductResponse200 = {
  data: void
  status: 200
}
    
export type campaignProductControllerRemoveProductResponseSuccess = (campaignProductControllerRemoveProductResponse200) & {
  headers: Headers;
};
;

export type campaignProductControllerRemoveProductResponse = (campaignProductControllerRemoveProductResponseSuccess)

export const getCampaignProductControllerRemoveProductUrl = (campaignId: string,
    id: string,) => {


  

  return `/campaigns/${campaignId}/products/${id}`
}

export const campaignProductControllerRemoveProduct = async (campaignId: string,
    id: string, options?: RequestInit): Promise<campaignProductControllerRemoveProductResponse> => {
  
  return defaultMutator<campaignProductControllerRemoveProductResponse>(getCampaignProductControllerRemoveProductUrl(campaignId,id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getCampaignProductControllerRemoveProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerRemoveProduct>>, TError,{campaignId: string;id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerRemoveProduct>>, TError,{campaignId: string;id: string}, TContext> => {

const mutationKey = ['campaignProductControllerRemoveProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignProductControllerRemoveProduct>>, {campaignId: string;id: string}> = (props) => {
          const {campaignId,id} = props ?? {};

          return  campaignProductControllerRemoveProduct(campaignId,id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignProductControllerRemoveProductMutationResult = NonNullable<Awaited<ReturnType<typeof campaignProductControllerRemoveProduct>>>
    
    export type CampaignProductControllerRemoveProductMutationError = unknown

    export const useCampaignProductControllerRemoveProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerRemoveProduct>>, TError,{campaignId: string;id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignProductControllerRemoveProduct>>,
        TError,
        {campaignId: string;id: string},
        TContext
      > => {
      return useMutation(getCampaignProductControllerRemoveProductMutationOptions(options), queryClient);
    }
    export type campaignProductControllerCreatePhaseResponse201 = {
  data: void
  status: 201
}
    
export type campaignProductControllerCreatePhaseResponseSuccess = (campaignProductControllerCreatePhaseResponse201) & {
  headers: Headers;
};
;

export type campaignProductControllerCreatePhaseResponse = (campaignProductControllerCreatePhaseResponseSuccess)

export const getCampaignProductControllerCreatePhaseUrl = (campaignId: string,
    productId: string,) => {


  

  return `/campaigns/${campaignId}/products/${productId}/phases`
}

export const campaignProductControllerCreatePhase = async (campaignId: string,
    productId: string,
    createPricingPhaseDto: CreatePricingPhaseDto, options?: RequestInit): Promise<campaignProductControllerCreatePhaseResponse> => {
  
  return defaultMutator<campaignProductControllerCreatePhaseResponse>(getCampaignProductControllerCreatePhaseUrl(campaignId,productId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPricingPhaseDto,)
  }
);}




export const getCampaignProductControllerCreatePhaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerCreatePhase>>, TError,{campaignId: string;productId: string;data: CreatePricingPhaseDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerCreatePhase>>, TError,{campaignId: string;productId: string;data: CreatePricingPhaseDto}, TContext> => {

const mutationKey = ['campaignProductControllerCreatePhase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignProductControllerCreatePhase>>, {campaignId: string;productId: string;data: CreatePricingPhaseDto}> = (props) => {
          const {campaignId,productId,data} = props ?? {};

          return  campaignProductControllerCreatePhase(campaignId,productId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignProductControllerCreatePhaseMutationResult = NonNullable<Awaited<ReturnType<typeof campaignProductControllerCreatePhase>>>
    export type CampaignProductControllerCreatePhaseMutationBody = CreatePricingPhaseDto
    export type CampaignProductControllerCreatePhaseMutationError = unknown

    export const useCampaignProductControllerCreatePhase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerCreatePhase>>, TError,{campaignId: string;productId: string;data: CreatePricingPhaseDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignProductControllerCreatePhase>>,
        TError,
        {campaignId: string;productId: string;data: CreatePricingPhaseDto},
        TContext
      > => {
      return useMutation(getCampaignProductControllerCreatePhaseMutationOptions(options), queryClient);
    }
    export type campaignProductControllerFindPhasesResponse200 = {
  data: void
  status: 200
}
    
export type campaignProductControllerFindPhasesResponseSuccess = (campaignProductControllerFindPhasesResponse200) & {
  headers: Headers;
};
;

export type campaignProductControllerFindPhasesResponse = (campaignProductControllerFindPhasesResponseSuccess)

export const getCampaignProductControllerFindPhasesUrl = (campaignId: string,
    productId: string,) => {


  

  return `/campaigns/${campaignId}/products/${productId}/phases`
}

export const campaignProductControllerFindPhases = async (campaignId: string,
    productId: string, options?: RequestInit): Promise<campaignProductControllerFindPhasesResponse> => {
  
  return defaultMutator<campaignProductControllerFindPhasesResponse>(getCampaignProductControllerFindPhasesUrl(campaignId,productId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignProductControllerFindPhasesQueryKey = (campaignId: string,
    productId: string,) => {
    return [
    `/campaigns/${campaignId}/products/${productId}/phases`
    ] as const;
    }

    
export const getCampaignProductControllerFindPhasesQueryOptions = <TData = Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError = unknown>(campaignId: string,
    productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignProductControllerFindPhasesQueryKey(campaignId,productId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignProductControllerFindPhases>>> = ({ signal }) => campaignProductControllerFindPhases(campaignId,productId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(campaignId && productId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignProductControllerFindPhasesQueryResult = NonNullable<Awaited<ReturnType<typeof campaignProductControllerFindPhases>>>
export type CampaignProductControllerFindPhasesQueryError = unknown


export function useCampaignProductControllerFindPhases<TData = Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError = unknown>(
 campaignId: string,
    productId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignProductControllerFindPhases>>,
          TError,
          Awaited<ReturnType<typeof campaignProductControllerFindPhases>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignProductControllerFindPhases<TData = Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError = unknown>(
 campaignId: string,
    productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignProductControllerFindPhases>>,
          TError,
          Awaited<ReturnType<typeof campaignProductControllerFindPhases>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignProductControllerFindPhases<TData = Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError = unknown>(
 campaignId: string,
    productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCampaignProductControllerFindPhases<TData = Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError = unknown>(
 campaignId: string,
    productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignProductControllerFindPhases>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignProductControllerFindPhasesQueryOptions(campaignId,productId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type campaignProductControllerUpdatePhaseResponse200 = {
  data: void
  status: 200
}
    
export type campaignProductControllerUpdatePhaseResponseSuccess = (campaignProductControllerUpdatePhaseResponse200) & {
  headers: Headers;
};
;

export type campaignProductControllerUpdatePhaseResponse = (campaignProductControllerUpdatePhaseResponseSuccess)

export const getCampaignProductControllerUpdatePhaseUrl = (campaignId: string,
    productId: string,
    id: string,) => {


  

  return `/campaigns/${campaignId}/products/${productId}/phases/${id}`
}

export const campaignProductControllerUpdatePhase = async (campaignId: string,
    productId: string,
    id: string,
    updatePricingPhaseDto: UpdatePricingPhaseDto, options?: RequestInit): Promise<campaignProductControllerUpdatePhaseResponse> => {
  
  return defaultMutator<campaignProductControllerUpdatePhaseResponse>(getCampaignProductControllerUpdatePhaseUrl(campaignId,productId,id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePricingPhaseDto,)
  }
);}




export const getCampaignProductControllerUpdatePhaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerUpdatePhase>>, TError,{campaignId: string;productId: string;id: string;data: UpdatePricingPhaseDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerUpdatePhase>>, TError,{campaignId: string;productId: string;id: string;data: UpdatePricingPhaseDto}, TContext> => {

const mutationKey = ['campaignProductControllerUpdatePhase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignProductControllerUpdatePhase>>, {campaignId: string;productId: string;id: string;data: UpdatePricingPhaseDto}> = (props) => {
          const {campaignId,productId,id,data} = props ?? {};

          return  campaignProductControllerUpdatePhase(campaignId,productId,id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignProductControllerUpdatePhaseMutationResult = NonNullable<Awaited<ReturnType<typeof campaignProductControllerUpdatePhase>>>
    export type CampaignProductControllerUpdatePhaseMutationBody = UpdatePricingPhaseDto
    export type CampaignProductControllerUpdatePhaseMutationError = unknown

    export const useCampaignProductControllerUpdatePhase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerUpdatePhase>>, TError,{campaignId: string;productId: string;id: string;data: UpdatePricingPhaseDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignProductControllerUpdatePhase>>,
        TError,
        {campaignId: string;productId: string;id: string;data: UpdatePricingPhaseDto},
        TContext
      > => {
      return useMutation(getCampaignProductControllerUpdatePhaseMutationOptions(options), queryClient);
    }
    export type campaignProductControllerRemovePhaseResponse200 = {
  data: void
  status: 200
}
    
export type campaignProductControllerRemovePhaseResponseSuccess = (campaignProductControllerRemovePhaseResponse200) & {
  headers: Headers;
};
;

export type campaignProductControllerRemovePhaseResponse = (campaignProductControllerRemovePhaseResponseSuccess)

export const getCampaignProductControllerRemovePhaseUrl = (campaignId: string,
    productId: string,
    id: string,) => {


  

  return `/campaigns/${campaignId}/products/${productId}/phases/${id}`
}

export const campaignProductControllerRemovePhase = async (campaignId: string,
    productId: string,
    id: string, options?: RequestInit): Promise<campaignProductControllerRemovePhaseResponse> => {
  
  return defaultMutator<campaignProductControllerRemovePhaseResponse>(getCampaignProductControllerRemovePhaseUrl(campaignId,productId,id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getCampaignProductControllerRemovePhaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerRemovePhase>>, TError,{campaignId: string;productId: string;id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerRemovePhase>>, TError,{campaignId: string;productId: string;id: string}, TContext> => {

const mutationKey = ['campaignProductControllerRemovePhase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignProductControllerRemovePhase>>, {campaignId: string;productId: string;id: string}> = (props) => {
          const {campaignId,productId,id} = props ?? {};

          return  campaignProductControllerRemovePhase(campaignId,productId,id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignProductControllerRemovePhaseMutationResult = NonNullable<Awaited<ReturnType<typeof campaignProductControllerRemovePhase>>>
    
    export type CampaignProductControllerRemovePhaseMutationError = unknown

    export const useCampaignProductControllerRemovePhase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignProductControllerRemovePhase>>, TError,{campaignId: string;productId: string;id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignProductControllerRemovePhase>>,
        TError,
        {campaignId: string;productId: string;id: string},
        TContext
      > => {
      return useMutation(getCampaignProductControllerRemovePhaseMutationOptions(options), queryClient);
    }
    