/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PublicEventOrderControllerFindPublicByOrderCode200
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type publicEventOrderControllerFindPublicByOrderCodeResponse200 = {
  data: PublicEventOrderControllerFindPublicByOrderCode200
  status: 200
}
    
export type publicEventOrderControllerFindPublicByOrderCodeResponseSuccess = (publicEventOrderControllerFindPublicByOrderCodeResponse200) & {
  headers: Headers;
};
;

export type publicEventOrderControllerFindPublicByOrderCodeResponse = (publicEventOrderControllerFindPublicByOrderCodeResponseSuccess)

export const getPublicEventOrderControllerFindPublicByOrderCodeUrl = (orderCode: string,) => {


  

  return `/event-orders/public/${orderCode}`
}

export const publicEventOrderControllerFindPublicByOrderCode = async (orderCode: string, options?: RequestInit): Promise<publicEventOrderControllerFindPublicByOrderCodeResponse> => {
  
  return defaultMutator<publicEventOrderControllerFindPublicByOrderCodeResponse>(getPublicEventOrderControllerFindPublicByOrderCodeUrl(orderCode),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPublicEventOrderControllerFindPublicByOrderCodeQueryKey = (orderCode: string,) => {
    return [
    `/event-orders/public/${orderCode}`
    ] as const;
    }

    
export const getPublicEventOrderControllerFindPublicByOrderCodeQueryOptions = <TData = Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError = unknown>(orderCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicEventOrderControllerFindPublicByOrderCodeQueryKey(orderCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>> = ({ signal }) => publicEventOrderControllerFindPublicByOrderCode(orderCode, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orderCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicEventOrderControllerFindPublicByOrderCodeQueryResult = NonNullable<Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>>
export type PublicEventOrderControllerFindPublicByOrderCodeQueryError = unknown


export function usePublicEventOrderControllerFindPublicByOrderCode<TData = Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError = unknown>(
 orderCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>,
          TError,
          Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicEventOrderControllerFindPublicByOrderCode<TData = Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError = unknown>(
 orderCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>,
          TError,
          Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicEventOrderControllerFindPublicByOrderCode<TData = Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError = unknown>(
 orderCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePublicEventOrderControllerFindPublicByOrderCode<TData = Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError = unknown>(
 orderCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventOrderControllerFindPublicByOrderCode>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicEventOrderControllerFindPublicByOrderCodeQueryOptions(orderCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




