/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFeedbackDto,
  FeedbackControllerCreate201,
  FeedbackControllerFindAll200,
  FeedbackControllerFindAllParams,
  FeedbackControllerFindOne200,
  FeedbackControllerRemove200,
  FeedbackControllerUpdateStatus200,
  UpdateFeedbackStatusDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type feedbackControllerCreateResponse201 = {
  data: FeedbackControllerCreate201
  status: 201
}
    
export type feedbackControllerCreateResponseSuccess = (feedbackControllerCreateResponse201) & {
  headers: Headers;
};
;

export type feedbackControllerCreateResponse = (feedbackControllerCreateResponseSuccess)

export const getFeedbackControllerCreateUrl = () => {


  

  return `/feedback`
}

export const feedbackControllerCreate = async (createFeedbackDto: CreateFeedbackDto, options?: RequestInit): Promise<feedbackControllerCreateResponse> => {
  
  return defaultMutator<feedbackControllerCreateResponse>(getFeedbackControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createFeedbackDto,)
  }
);}




export const getFeedbackControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof feedbackControllerCreate>>, TError,{data: CreateFeedbackDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof feedbackControllerCreate>>, TError,{data: CreateFeedbackDto}, TContext> => {

const mutationKey = ['feedbackControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof feedbackControllerCreate>>, {data: CreateFeedbackDto}> = (props) => {
          const {data} = props ?? {};

          return  feedbackControllerCreate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FeedbackControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof feedbackControllerCreate>>>
    export type FeedbackControllerCreateMutationBody = CreateFeedbackDto
    export type FeedbackControllerCreateMutationError = unknown

    export const useFeedbackControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof feedbackControllerCreate>>, TError,{data: CreateFeedbackDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof feedbackControllerCreate>>,
        TError,
        {data: CreateFeedbackDto},
        TContext
      > => {
      return useMutation(getFeedbackControllerCreateMutationOptions(options), queryClient);
    }
    export type feedbackControllerFindAllResponse200 = {
  data: FeedbackControllerFindAll200
  status: 200
}
    
export type feedbackControllerFindAllResponseSuccess = (feedbackControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type feedbackControllerFindAllResponse = (feedbackControllerFindAllResponseSuccess)

export const getFeedbackControllerFindAllUrl = (params: FeedbackControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/feedback?${stringifiedParams}` : `/feedback`
}

export const feedbackControllerFindAll = async (params: FeedbackControllerFindAllParams, options?: RequestInit): Promise<feedbackControllerFindAllResponse> => {
  
  return defaultMutator<feedbackControllerFindAllResponse>(getFeedbackControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getFeedbackControllerFindAllQueryKey = (params?: FeedbackControllerFindAllParams,) => {
    return [
    `/feedback`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getFeedbackControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError = unknown>(params: FeedbackControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFeedbackControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof feedbackControllerFindAll>>> = ({ signal }) => feedbackControllerFindAll(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FeedbackControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof feedbackControllerFindAll>>>
export type FeedbackControllerFindAllQueryError = unknown


export function useFeedbackControllerFindAll<TData = Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError = unknown>(
 params: FeedbackControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof feedbackControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof feedbackControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFeedbackControllerFindAll<TData = Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError = unknown>(
 params: FeedbackControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof feedbackControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof feedbackControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFeedbackControllerFindAll<TData = Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError = unknown>(
 params: FeedbackControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFeedbackControllerFindAll<TData = Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError = unknown>(
 params: FeedbackControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFeedbackControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type feedbackControllerFindOneResponse200 = {
  data: FeedbackControllerFindOne200
  status: 200
}
    
export type feedbackControllerFindOneResponseSuccess = (feedbackControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type feedbackControllerFindOneResponse = (feedbackControllerFindOneResponseSuccess)

export const getFeedbackControllerFindOneUrl = (id: string,) => {


  

  return `/feedback/${id}`
}

export const feedbackControllerFindOne = async (id: string, options?: RequestInit): Promise<feedbackControllerFindOneResponse> => {
  
  return defaultMutator<feedbackControllerFindOneResponse>(getFeedbackControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getFeedbackControllerFindOneQueryKey = (id: string,) => {
    return [
    `/feedback/${id}`
    ] as const;
    }

    
export const getFeedbackControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFeedbackControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof feedbackControllerFindOne>>> = ({ signal }) => feedbackControllerFindOne(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FeedbackControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof feedbackControllerFindOne>>>
export type FeedbackControllerFindOneQueryError = unknown


export function useFeedbackControllerFindOne<TData = Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof feedbackControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof feedbackControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFeedbackControllerFindOne<TData = Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof feedbackControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof feedbackControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFeedbackControllerFindOne<TData = Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFeedbackControllerFindOne<TData = Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof feedbackControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFeedbackControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type feedbackControllerRemoveResponse200 = {
  data: FeedbackControllerRemove200
  status: 200
}
    
export type feedbackControllerRemoveResponseSuccess = (feedbackControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type feedbackControllerRemoveResponse = (feedbackControllerRemoveResponseSuccess)

export const getFeedbackControllerRemoveUrl = (id: string,) => {


  

  return `/feedback/${id}`
}

export const feedbackControllerRemove = async (id: string, options?: RequestInit): Promise<feedbackControllerRemoveResponse> => {
  
  return defaultMutator<feedbackControllerRemoveResponse>(getFeedbackControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getFeedbackControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof feedbackControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof feedbackControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['feedbackControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof feedbackControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  feedbackControllerRemove(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FeedbackControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof feedbackControllerRemove>>>
    
    export type FeedbackControllerRemoveMutationError = unknown

    export const useFeedbackControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof feedbackControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof feedbackControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getFeedbackControllerRemoveMutationOptions(options), queryClient);
    }
    export type feedbackControllerUpdateStatusResponse200 = {
  data: FeedbackControllerUpdateStatus200
  status: 200
}
    
export type feedbackControllerUpdateStatusResponseSuccess = (feedbackControllerUpdateStatusResponse200) & {
  headers: Headers;
};
;

export type feedbackControllerUpdateStatusResponse = (feedbackControllerUpdateStatusResponseSuccess)

export const getFeedbackControllerUpdateStatusUrl = (id: string,) => {


  

  return `/feedback/${id}/status`
}

export const feedbackControllerUpdateStatus = async (id: string,
    updateFeedbackStatusDto: UpdateFeedbackStatusDto, options?: RequestInit): Promise<feedbackControllerUpdateStatusResponse> => {
  
  return defaultMutator<feedbackControllerUpdateStatusResponse>(getFeedbackControllerUpdateStatusUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateFeedbackStatusDto,)
  }
);}




export const getFeedbackControllerUpdateStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof feedbackControllerUpdateStatus>>, TError,{id: string;data: UpdateFeedbackStatusDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof feedbackControllerUpdateStatus>>, TError,{id: string;data: UpdateFeedbackStatusDto}, TContext> => {

const mutationKey = ['feedbackControllerUpdateStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof feedbackControllerUpdateStatus>>, {id: string;data: UpdateFeedbackStatusDto}> = (props) => {
          const {id,data} = props ?? {};

          return  feedbackControllerUpdateStatus(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FeedbackControllerUpdateStatusMutationResult = NonNullable<Awaited<ReturnType<typeof feedbackControllerUpdateStatus>>>
    export type FeedbackControllerUpdateStatusMutationBody = UpdateFeedbackStatusDto
    export type FeedbackControllerUpdateStatusMutationError = unknown

    export const useFeedbackControllerUpdateStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof feedbackControllerUpdateStatus>>, TError,{id: string;data: UpdateFeedbackStatusDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof feedbackControllerUpdateStatus>>,
        TError,
        {id: string;data: UpdateFeedbackStatusDto},
        TContext
      > => {
      return useMutation(getFeedbackControllerUpdateStatusMutationOptions(options), queryClient);
    }
    