/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Athlete,
  AthleteControllerFindAllParams,
  AthleteControllerGetStatsParams,
  AthleteControllerSearchParams,
  AthleteStats,
  CreateAthleteDto,
  UpdateAthleteDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create athlete profile
 */
export type athleteControllerCreateResponse201 = {
  data: Athlete
  status: 201
}

export type athleteControllerCreateResponse409 = {
  data: void
  status: 409
}
    
export type athleteControllerCreateResponseSuccess = (athleteControllerCreateResponse201) & {
  headers: Headers;
};
export type athleteControllerCreateResponseError = (athleteControllerCreateResponse409) & {
  headers: Headers;
};

export type athleteControllerCreateResponse = (athleteControllerCreateResponseSuccess | athleteControllerCreateResponseError)

export const getAthleteControllerCreateUrl = () => {


  

  return `/athletes`
}

export const athleteControllerCreate = async (createAthleteDto: CreateAthleteDto, options?: RequestInit): Promise<athleteControllerCreateResponse> => {
  
  return defaultMutator<athleteControllerCreateResponse>(getAthleteControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAthleteDto,)
  }
);}




export const getAthleteControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof athleteControllerCreate>>, TError,{data: CreateAthleteDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof athleteControllerCreate>>, TError,{data: CreateAthleteDto}, TContext> => {

const mutationKey = ['athleteControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof athleteControllerCreate>>, {data: CreateAthleteDto}> = (props) => {
          const {data} = props ?? {};

          return  athleteControllerCreate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AthleteControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof athleteControllerCreate>>>
    export type AthleteControllerCreateMutationBody = CreateAthleteDto
    export type AthleteControllerCreateMutationError = void

    /**
 * @summary Create athlete profile
 */
export const useAthleteControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof athleteControllerCreate>>, TError,{data: CreateAthleteDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof athleteControllerCreate>>,
        TError,
        {data: CreateAthleteDto},
        TContext
      > => {
      return useMutation(getAthleteControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all athletes with filters
 */
export type athleteControllerFindAllResponse200 = {
  data: Athlete[]
  status: 200
}
    
export type athleteControllerFindAllResponseSuccess = (athleteControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type athleteControllerFindAllResponse = (athleteControllerFindAllResponseSuccess)

export const getAthleteControllerFindAllUrl = (params?: AthleteControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/athletes?${stringifiedParams}` : `/athletes`
}

export const athleteControllerFindAll = async (params?: AthleteControllerFindAllParams, options?: RequestInit): Promise<athleteControllerFindAllResponse> => {
  
  return defaultMutator<athleteControllerFindAllResponse>(getAthleteControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getAthleteControllerFindAllQueryKey = (params?: AthleteControllerFindAllParams,) => {
    return [
    `/athletes`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAthleteControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof athleteControllerFindAll>>, TError = unknown>(params?: AthleteControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAthleteControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof athleteControllerFindAll>>> = ({ signal }) => athleteControllerFindAll(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AthleteControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof athleteControllerFindAll>>>
export type AthleteControllerFindAllQueryError = unknown


export function useAthleteControllerFindAll<TData = Awaited<ReturnType<typeof athleteControllerFindAll>>, TError = unknown>(
 params: undefined |  AthleteControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerFindAll<TData = Awaited<ReturnType<typeof athleteControllerFindAll>>, TError = unknown>(
 params?: AthleteControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerFindAll<TData = Awaited<ReturnType<typeof athleteControllerFindAll>>, TError = unknown>(
 params?: AthleteControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all athletes with filters
 */

export function useAthleteControllerFindAll<TData = Awaited<ReturnType<typeof athleteControllerFindAll>>, TError = unknown>(
 params?: AthleteControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAthleteControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Search athletes by name
 */
export type athleteControllerSearchResponse200 = {
  data: Athlete[]
  status: 200
}
    
export type athleteControllerSearchResponseSuccess = (athleteControllerSearchResponse200) & {
  headers: Headers;
};
;

export type athleteControllerSearchResponse = (athleteControllerSearchResponseSuccess)

export const getAthleteControllerSearchUrl = (params: AthleteControllerSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/athletes/search?${stringifiedParams}` : `/athletes/search`
}

export const athleteControllerSearch = async (params: AthleteControllerSearchParams, options?: RequestInit): Promise<athleteControllerSearchResponse> => {
  
  return defaultMutator<athleteControllerSearchResponse>(getAthleteControllerSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getAthleteControllerSearchQueryKey = (params?: AthleteControllerSearchParams,) => {
    return [
    `/athletes/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAthleteControllerSearchQueryOptions = <TData = Awaited<ReturnType<typeof athleteControllerSearch>>, TError = unknown>(params: AthleteControllerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerSearch>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAthleteControllerSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof athleteControllerSearch>>> = ({ signal }) => athleteControllerSearch(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof athleteControllerSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AthleteControllerSearchQueryResult = NonNullable<Awaited<ReturnType<typeof athleteControllerSearch>>>
export type AthleteControllerSearchQueryError = unknown


export function useAthleteControllerSearch<TData = Awaited<ReturnType<typeof athleteControllerSearch>>, TError = unknown>(
 params: AthleteControllerSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerSearch<TData = Awaited<ReturnType<typeof athleteControllerSearch>>, TError = unknown>(
 params: AthleteControllerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerSearch<TData = Awaited<ReturnType<typeof athleteControllerSearch>>, TError = unknown>(
 params: AthleteControllerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerSearch>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search athletes by name
 */

export function useAthleteControllerSearch<TData = Awaited<ReturnType<typeof athleteControllerSearch>>, TError = unknown>(
 params: AthleteControllerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerSearch>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAthleteControllerSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get my athlete profiles
 */
export type athleteControllerGetMyProfilesResponse200 = {
  data: Athlete[]
  status: 200
}
    
export type athleteControllerGetMyProfilesResponseSuccess = (athleteControllerGetMyProfilesResponse200) & {
  headers: Headers;
};
;

export type athleteControllerGetMyProfilesResponse = (athleteControllerGetMyProfilesResponseSuccess)

export const getAthleteControllerGetMyProfilesUrl = () => {


  

  return `/athletes/my-profiles`
}

export const athleteControllerGetMyProfiles = async ( options?: RequestInit): Promise<athleteControllerGetMyProfilesResponse> => {
  
  return defaultMutator<athleteControllerGetMyProfilesResponse>(getAthleteControllerGetMyProfilesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getAthleteControllerGetMyProfilesQueryKey = () => {
    return [
    `/athletes/my-profiles`
    ] as const;
    }

    
export const getAthleteControllerGetMyProfilesQueryOptions = <TData = Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAthleteControllerGetMyProfilesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>> = ({ signal }) => athleteControllerGetMyProfiles({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AthleteControllerGetMyProfilesQueryResult = NonNullable<Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>>
export type AthleteControllerGetMyProfilesQueryError = unknown


export function useAthleteControllerGetMyProfiles<TData = Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerGetMyProfiles<TData = Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerGetMyProfiles<TData = Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my athlete profiles
 */

export function useAthleteControllerGetMyProfiles<TData = Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetMyProfiles>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAthleteControllerGetMyProfilesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get athlete by ID
 */
export type athleteControllerFindOneResponse200 = {
  data: Athlete
  status: 200
}

export type athleteControllerFindOneResponse404 = {
  data: void
  status: 404
}
    
export type athleteControllerFindOneResponseSuccess = (athleteControllerFindOneResponse200) & {
  headers: Headers;
};
export type athleteControllerFindOneResponseError = (athleteControllerFindOneResponse404) & {
  headers: Headers;
};

export type athleteControllerFindOneResponse = (athleteControllerFindOneResponseSuccess | athleteControllerFindOneResponseError)

export const getAthleteControllerFindOneUrl = (id: string,) => {


  

  return `/athletes/${id}`
}

export const athleteControllerFindOne = async (id: string, options?: RequestInit): Promise<athleteControllerFindOneResponse> => {
  
  return defaultMutator<athleteControllerFindOneResponse>(getAthleteControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getAthleteControllerFindOneQueryKey = (id: string,) => {
    return [
    `/athletes/${id}`
    ] as const;
    }

    
export const getAthleteControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof athleteControllerFindOne>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAthleteControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof athleteControllerFindOne>>> = ({ signal }) => athleteControllerFindOne(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AthleteControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof athleteControllerFindOne>>>
export type AthleteControllerFindOneQueryError = void


export function useAthleteControllerFindOne<TData = Awaited<ReturnType<typeof athleteControllerFindOne>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerFindOne<TData = Awaited<ReturnType<typeof athleteControllerFindOne>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerFindOne<TData = Awaited<ReturnType<typeof athleteControllerFindOne>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get athlete by ID
 */

export function useAthleteControllerFindOne<TData = Awaited<ReturnType<typeof athleteControllerFindOne>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAthleteControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update athlete profile
 */
export type athleteControllerUpdateResponse200 = {
  data: Athlete
  status: 200
}

export type athleteControllerUpdateResponse403 = {
  data: void
  status: 403
}

export type athleteControllerUpdateResponse404 = {
  data: void
  status: 404
}
    
export type athleteControllerUpdateResponseSuccess = (athleteControllerUpdateResponse200) & {
  headers: Headers;
};
export type athleteControllerUpdateResponseError = (athleteControllerUpdateResponse403 | athleteControllerUpdateResponse404) & {
  headers: Headers;
};

export type athleteControllerUpdateResponse = (athleteControllerUpdateResponseSuccess | athleteControllerUpdateResponseError)

export const getAthleteControllerUpdateUrl = (id: string,) => {


  

  return `/athletes/${id}`
}

export const athleteControllerUpdate = async (id: string,
    updateAthleteDto: UpdateAthleteDto, options?: RequestInit): Promise<athleteControllerUpdateResponse> => {
  
  return defaultMutator<athleteControllerUpdateResponse>(getAthleteControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateAthleteDto,)
  }
);}




export const getAthleteControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof athleteControllerUpdate>>, TError,{id: string;data: UpdateAthleteDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof athleteControllerUpdate>>, TError,{id: string;data: UpdateAthleteDto}, TContext> => {

const mutationKey = ['athleteControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof athleteControllerUpdate>>, {id: string;data: UpdateAthleteDto}> = (props) => {
          const {id,data} = props ?? {};

          return  athleteControllerUpdate(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AthleteControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof athleteControllerUpdate>>>
    export type AthleteControllerUpdateMutationBody = UpdateAthleteDto
    export type AthleteControllerUpdateMutationError = void

    /**
 * @summary Update athlete profile
 */
export const useAthleteControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof athleteControllerUpdate>>, TError,{id: string;data: UpdateAthleteDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof athleteControllerUpdate>>,
        TError,
        {id: string;data: UpdateAthleteDto},
        TContext
      > => {
      return useMutation(getAthleteControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete athlete profile
 */
export type athleteControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type athleteControllerRemoveResponse403 = {
  data: void
  status: 403
}

export type athleteControllerRemoveResponse404 = {
  data: void
  status: 404
}
    
export type athleteControllerRemoveResponseSuccess = (athleteControllerRemoveResponse200) & {
  headers: Headers;
};
export type athleteControllerRemoveResponseError = (athleteControllerRemoveResponse403 | athleteControllerRemoveResponse404) & {
  headers: Headers;
};

export type athleteControllerRemoveResponse = (athleteControllerRemoveResponseSuccess | athleteControllerRemoveResponseError)

export const getAthleteControllerRemoveUrl = (id: string,) => {


  

  return `/athletes/${id}`
}

export const athleteControllerRemove = async (id: string, options?: RequestInit): Promise<athleteControllerRemoveResponse> => {
  
  return defaultMutator<athleteControllerRemoveResponse>(getAthleteControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getAthleteControllerRemoveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof athleteControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof athleteControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['athleteControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof athleteControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  athleteControllerRemove(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AthleteControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof athleteControllerRemove>>>
    
    export type AthleteControllerRemoveMutationError = void

    /**
 * @summary Delete athlete profile
 */
export const useAthleteControllerRemove = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof athleteControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof athleteControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getAthleteControllerRemoveMutationOptions(options), queryClient);
    }
    /**
 * @summary Get athlete statistics history
 */
export type athleteControllerGetStatsResponse200 = {
  data: AthleteStats[]
  status: 200
}
    
export type athleteControllerGetStatsResponseSuccess = (athleteControllerGetStatsResponse200) & {
  headers: Headers;
};
;

export type athleteControllerGetStatsResponse = (athleteControllerGetStatsResponseSuccess)

export const getAthleteControllerGetStatsUrl = (id: string,
    params?: AthleteControllerGetStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/athletes/${id}/stats?${stringifiedParams}` : `/athletes/${id}/stats`
}

export const athleteControllerGetStats = async (id: string,
    params?: AthleteControllerGetStatsParams, options?: RequestInit): Promise<athleteControllerGetStatsResponse> => {
  
  return defaultMutator<athleteControllerGetStatsResponse>(getAthleteControllerGetStatsUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getAthleteControllerGetStatsQueryKey = (id: string,
    params?: AthleteControllerGetStatsParams,) => {
    return [
    `/athletes/${id}/stats`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAthleteControllerGetStatsQueryOptions = <TData = Awaited<ReturnType<typeof athleteControllerGetStats>>, TError = unknown>(id: string,
    params?: AthleteControllerGetStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetStats>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAthleteControllerGetStatsQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof athleteControllerGetStats>>> = ({ signal }) => athleteControllerGetStats(id,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AthleteControllerGetStatsQueryResult = NonNullable<Awaited<ReturnType<typeof athleteControllerGetStats>>>
export type AthleteControllerGetStatsQueryError = unknown


export function useAthleteControllerGetStats<TData = Awaited<ReturnType<typeof athleteControllerGetStats>>, TError = unknown>(
 id: string,
    params: undefined |  AthleteControllerGetStatsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerGetStats>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerGetStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerGetStats<TData = Awaited<ReturnType<typeof athleteControllerGetStats>>, TError = unknown>(
 id: string,
    params?: AthleteControllerGetStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof athleteControllerGetStats>>,
          TError,
          Awaited<ReturnType<typeof athleteControllerGetStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAthleteControllerGetStats<TData = Awaited<ReturnType<typeof athleteControllerGetStats>>, TError = unknown>(
 id: string,
    params?: AthleteControllerGetStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetStats>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get athlete statistics history
 */

export function useAthleteControllerGetStats<TData = Awaited<ReturnType<typeof athleteControllerGetStats>>, TError = unknown>(
 id: string,
    params?: AthleteControllerGetStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof athleteControllerGetStats>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAthleteControllerGetStatsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




