/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PublicEventControllerFindAll200,
  PublicEventControllerFindAllParams,
  PublicEventControllerFindOne200
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Lấy danh sách sự kiện đã xuất bản, hỗ trợ lọc theo loại thể thao và tìm kiếm tên
 * @summary Danh sách sự kiện (công khai)
 */
export type publicEventControllerFindAllResponse200 = {
  data: PublicEventControllerFindAll200
  status: 200
}
    
export type publicEventControllerFindAllResponseSuccess = (publicEventControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type publicEventControllerFindAllResponse = (publicEventControllerFindAllResponseSuccess)

export const getPublicEventControllerFindAllUrl = (params?: PublicEventControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/public/events?${stringifiedParams}` : `/public/events`
}

export const publicEventControllerFindAll = async (params?: PublicEventControllerFindAllParams, options?: RequestInit): Promise<publicEventControllerFindAllResponse> => {
  
  return defaultMutator<publicEventControllerFindAllResponse>(getPublicEventControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPublicEventControllerFindAllQueryKey = (params?: PublicEventControllerFindAllParams,) => {
    return [
    `/public/events`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getPublicEventControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError = unknown>(params?: PublicEventControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicEventControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicEventControllerFindAll>>> = ({ signal }) => publicEventControllerFindAll(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicEventControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof publicEventControllerFindAll>>>
export type PublicEventControllerFindAllQueryError = unknown


export function usePublicEventControllerFindAll<TData = Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError = unknown>(
 params: undefined |  PublicEventControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicEventControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof publicEventControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicEventControllerFindAll<TData = Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError = unknown>(
 params?: PublicEventControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicEventControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof publicEventControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicEventControllerFindAll<TData = Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError = unknown>(
 params?: PublicEventControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Danh sách sự kiện (công khai)
 */

export function usePublicEventControllerFindAll<TData = Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError = unknown>(
 params?: PublicEventControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicEventControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Lấy thông tin chi tiết sự kiện không cần đăng nhập
 * @summary Chi tiết sự kiện (công khai)
 */
export type publicEventControllerFindOneResponse200 = {
  data: PublicEventControllerFindOne200
  status: 200
}
    
export type publicEventControllerFindOneResponseSuccess = (publicEventControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type publicEventControllerFindOneResponse = (publicEventControllerFindOneResponseSuccess)

export const getPublicEventControllerFindOneUrl = (id: string,) => {


  

  return `/public/events/${id}`
}

export const publicEventControllerFindOne = async (id: string, options?: RequestInit): Promise<publicEventControllerFindOneResponse> => {
  
  return defaultMutator<publicEventControllerFindOneResponse>(getPublicEventControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPublicEventControllerFindOneQueryKey = (id: string,) => {
    return [
    `/public/events/${id}`
    ] as const;
    }

    
export const getPublicEventControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicEventControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicEventControllerFindOne>>> = ({ signal }) => publicEventControllerFindOne(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicEventControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof publicEventControllerFindOne>>>
export type PublicEventControllerFindOneQueryError = unknown


export function usePublicEventControllerFindOne<TData = Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicEventControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof publicEventControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicEventControllerFindOne<TData = Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicEventControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof publicEventControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicEventControllerFindOne<TData = Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Chi tiết sự kiện (công khai)
 */

export function usePublicEventControllerFindOne<TData = Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicEventControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicEventControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




