/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { AddMediaDtoType } from './addMediaDtoType';

export interface AddMediaDto {
  /** Loại media */
  type: AddMediaDtoType;
  /** URL của media */
  url: string;
  /** Kích thước file (bytes) */
  fileSize: number;
  /** MIME type của file */
  mimeType: string;
}
