/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export type AthleteControllerGetStatsParams = {
/**
 * Start date (ISO format)
 */
startDate?: string;
/**
 * End date (ISO format)
 */
endDate?: string;
};
