/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { Athlete } from './athlete';

export interface AthleteStats {
  /** Stats record ID */
  id: string;
  /** Athlete ID */
  athleteId: string;
  /** Athlete relationship */
  athlete: Athlete;
  /** Stats date */
  date: string;
  /** Rating on this date */
  rating: number;
  /** Matches played on this date */
  matchesPlayed: number;
  /** Wins on this date */
  wins: number;
  /** Losses on this date */
  losses: number;
  /** Events participated on this date */
  eventsParticipated: number;
}
