/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Size áo
 */
export type AthleteInfoDtoSizeShirt = typeof AthleteInfoDtoSizeShirt[keyof typeof AthleteInfoDtoSizeShirt];


export const AthleteInfoDtoSizeShirt = {
  XS: 'XS',
  S: 'S',
  M: 'M',
  L: 'L',
  XL: 'XL',
  XXL: 'XXL',
} as const;
