/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Giới tính
 */
export type AthleteInfoDtoGender = typeof AthleteInfoDtoGender[keyof typeof AthleteInfoDtoGender];


export const AthleteInfoDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;
