/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface AthleteInfoDto {
  /** Cự ly đăng ký */
  distance: string;
  /** Họ và tên đệm */
  lastName: string;
  /** Tên */
  firstName: string;
  /** Số điện thoại */
  phoneNumber: string;
  /** Số CCCD / Hộ chiếu */
  identityCard?: string;
  /** Địa chỉ */
  location?: string;
  /** Quốc tịch */
  national?: string;
  /** Mã tỉnh/thành phố (lấy từ API province) */
  provinceCode?: string;
  /** Ngày sinh */
  dateOfBirth?: string;
  /** Size áo (theo danh sách sizeShirtOptions của campaign) */
  sizeShirt?: string;
  /** Câu lạc bộ */
  club?: string;
  /** Tên trên BIB */
  nameInBib?: string;
  /** SĐT người liên hệ y tế */
  medicalInformationPhoneNumber?: string;
  /** Tên người liên hệ y tế */
  medicalInformationName?: string;
  /** Thông tin y tế */
  medicalInformation?: string;
  /** Loại thuốc đang dùng */
  typeOfMedicine?: string;
  /** Nhóm máu */
  bloodType?: string;
}
