/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export type AthleteControllerFindAllSortBy = typeof AthleteControllerFindAllSortBy[keyof typeof AthleteControllerFindAllSortBy];


export const AthleteControllerFindAllSortBy = {
  name: 'name',
  currentRating: 'currentRating',
  totalMatches: 'totalMatches',
  winRate: 'winRate',
  createdAt: 'createdAt',
} as const;
