/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDto } from './userResponseDto';

export type AuthControllerGetProfile200 = {
  status?: string;
  code?: number;
  data?: UserResponseDto;
};
