/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface BadmintonChangeEndsDto {
  /** Đổi sân sau mỗi set */
  endOfSet: boolean;
  /** Đổi sân/Nghỉ khi chạm 11 điểm ở set 3 */
  interval: boolean;
}
