/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface BlacklistResponseDto {
  /** ID mục blacklist */
  id: string;
  /** ID sự kiện */
  eventId: string;
  /** Loại (EMAIL/PHONE) */
  type: string;
  /** Giá trị (email hoặc SĐT) */
  value: string;
  /** Ngày tạo */
  created_at: string;
}
