/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { CampaignResponseDtoPaymentConfig } from './campaignResponseDtoPaymentConfig';
import type { CampaignResponseDtoStatus } from './campaignResponseDtoStatus';
import type { DistanceItemResponseDto } from './distanceItemResponseDto';

export interface CampaignResponseDto {
  id: string;
  creatorId: string;
  name: string;
  slug: string;
  description?: string;
  bannerUrl?: string;
  startTime: string;
  endTime: string;
  status: CampaignResponseDtoStatus;
  distances: DistanceItemResponseDto[];
  groupName?: string;
  groupLeader?: string;
  zaloGroupUrl?: string;
  hotline?: string;
  regulationsUrl?: string;
  regulations?: string;
  fanpageUrl?: string;
  sizeShirtOptions?: string[];
  paymentConfig?: CampaignResponseDtoPaymentConfig;
  createdAt: string;
  updatedAt: string;
}
