/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { CampaignPublicResponseDtoStatus } from './campaignPublicResponseDtoStatus';
import type { DistanceItemResponseDto } from './distanceItemResponseDto';

export interface CampaignPublicResponseDto {
  /** ID chiến dịch */
  id: string;
  /** Tên chiến dịch */
  name: string;
  /** Slug URL */
  slug: string;
  /** Mô tả */
  description?: string;
  /** Ảnh banner */
  bannerUrl?: string;
  /** Thời gian bắt đầu */
  startTime: string;
  /** Thời gian kết thúc */
  endTime: string;
  /** Trạng thái */
  status: CampaignPublicResponseDtoStatus;
  /** Danh sách cự ly và giá */
  distances: DistanceItemResponseDto[];
  /** Tên nhóm */
  groupName?: string;
  /** Trưởng nhóm */
  groupLeader?: string;
  /** Link nhóm Zalo */
  zaloGroupUrl?: string;
  /** Hotline liên hệ */
  hotline?: string;
  /** Link điều lệ */
  regulationsUrl?: string;
  /** Link fanpage */
  fanpageUrl?: string;
  /** Danh sách size áo */
  sizeShirtOptions?: string[];
  /** Thời gian tạo */
  createdAt: string;
  /** Thời gian cập nhật */
  updatedAt: string;
}
