/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Trạng thái
 */
export type CampaignPublicResponseDtoStatus = typeof CampaignPublicResponseDtoStatus[keyof typeof CampaignPublicResponseDtoStatus];


export const CampaignPublicResponseDtoStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
} as const;
