/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { CourtStatus } from './courtStatus';

export interface Court {
  /** Court unique identifier */
  id: string;
  /** Event ID */
  eventId: string;
  /** Court name */
  name: string;
  /** Sort order */
  sortOrder: number;
  /** Court status */
  status: CourtStatus;
  /** Access secret for QR authentication */
  accessSecret: string;
  /** Is ghost/holding court */
  isGhost: boolean;
  /** Allowed session IDs for category filtering */
  allowedSessionIds?: string[];
}
