/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export type CreateEventSessionDtoRatingSourcesItem = typeof CreateEventSessionDtoRatingSourcesItem[keyof typeof CreateEventSessionDtoRatingSourcesItem];


export const CreateEventSessionDtoRatingSourcesItem = {
  MANUAL: 'MANUAL',
  FIVE_RATING: 'FIVE_RATING',
  DUPR: 'DUPR',
} as const;
