/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { CreateStageDtoConfig } from './createStageDtoConfig';
import type { CreateStageDtoStageType } from './createStageDtoStageType';

export interface CreateStageDto {
  /**
   * Stage name
   * @maxLength 256
   */
  name: string;
  /** Stage type */
  stageType: CreateStageDtoStageType;
  /** Stage configuration (varies by type). Round Robin: { groupCount, advancePerGroup, playoffType }. Elimination: { seedingType }. Flex: {} */
  config?: CreateStageDtoConfig;
  /** Sort order */
  sortOrder?: number;
}
