/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { CreateCampaignDtoPaymentConfig } from './createCampaignDtoPaymentConfig';
import type { DistanceItemDto } from './distanceItemDto';

export interface CreateCampaignDto {
  name: string;
  slug: string;
  description?: string;
  bannerUrl?: string;
  startTime: string;
  endTime: string;
  /** Danh sách cự ly và giá */
  distances?: DistanceItemDto[];
  /** Tên nhóm */
  groupName?: string;
  /** Trưởng nhóm */
  groupLeader?: string;
  /** Link nhóm Zalo */
  zaloGroupUrl?: string;
  /** Hotline */
  hotline?: string;
  /** Link điều lệ giải */
  regulationsUrl?: string;
  /** Link fanpage */
  fanpageUrl?: string;
  paymentConfig?: CreateCampaignDtoPaymentConfig;
}
