/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { OrderItemDto } from './orderItemDto';

export interface CreateOrderDto {
  /** Họ và tên đệm */
  lastName: string;
  /** Tên */
  firstName: string;
  email?: string;
  phoneNumber: string;
  items: OrderItemDto[];
}
