/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { CreateCampaignDtoPaymentConfig } from './createCampaignDtoPaymentConfig';

export interface CreateCampaignDto {
  name: string;
  slug: string;
  description?: string;
  bannerUrl?: string;
  startTime: string;
  endTime: string;
  paymentConfig?: CreateCampaignDtoPaymentConfig;
}
