/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { CreateParticipantDtoCustomData } from './createParticipantDtoCustomData';

export interface CreateParticipantDto {
  /** Event ID */
  eventId: string;
  /** Event session ID */
  sessionId?: string;
  /** Athlete ID */
  athleteId: string;
  /** Partner athlete ID (for doubles) */
  partnerId?: string;
  /** Custom data */
  customData?: CreateParticipantDtoCustomData;
}
