/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Thể thức thi đấu
 */
export type CreateEventSessionDtoMatchType = typeof CreateEventSessionDtoMatchType[keyof typeof CreateEventSessionDtoMatchType];


export const CreateEventSessionDtoMatchType = {
  SINGLES: 'SINGLES',
  DOUBLES: 'DOUBLES',
} as const;
