/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Stage type
 */
export type CreateStageDtoStageType = typeof CreateStageDtoStageType[keyof typeof CreateStageDtoStageType];


export const CreateStageDtoStageType = {
  ROUND_ROBIN_PLAYOFF: 'ROUND_ROBIN_PLAYOFF',
  SINGLE_ELIMINATION: 'SINGLE_ELIMINATION',
  DOUBLE_ELIMINATION: 'DOUBLE_ELIMINATION',
  FLEX: 'FLEX',
} as const;
