/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export type CreateFeedbackDtoCategory = typeof CreateFeedbackDtoCategory[keyof typeof CreateFeedbackDtoCategory];


export const CreateFeedbackDtoCategory = {
  GENERAL: 'GENERAL',
  EVENT: 'EVENT',
  PAYMENT: 'PAYMENT',
  UI_UX: 'UI_UX',
  BUG: 'BUG',
  SUGGESTION: 'SUGGESTION',
} as const;
