/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { CreateFeedbackDtoCategory } from './createFeedbackDtoCategory';

export interface CreateFeedbackDto {
  name: string;
  email: string;
  phone?: string;
  category: CreateFeedbackDtoCategory;
  content: string;
  rating?: number;
}
