/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface CreateCourtDto {
  /** Court name */
  name: string;
  /** Allowed session IDs for category filtering */
  allowedSessionIds?: string[];
  /** Is ghost/holding court */
  isGhost?: boolean;
}
