/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface CustomFieldResponseDto {
  /** ID trường dữ liệu */
  id: string;
  /** ID sự kiện */
  eventId: string;
  /** Label hiển thị */
  label: string;
  /** Tên trường */
  fieldName: string;
  /** Mô tả */
  description?: string;
  /** Loại trường */
  fieldType: string;
  /** Các lựa chọn */
  options?: unknown[][];
  /** Định dạng file cho phép */
  allowedFileTypes?: unknown[][];
  /** Giá trị mặc định */
  defaultValue?: string;
  /** URL ảnh đính kèm */
  attachmentUrl?: string;
  /** Mapping DB */
  dbMapping?: string;
  /** Bắt buộc */
  isRequired: boolean;
  /** Hiển thị */
  isVisible: boolean;
  /** Thứ tự hiển thị */
  sortOrder: number;
  /** Ngày tạo */
  created_at: string;
  /** Ngày cập nhật */
  updated_at: string;
}
