/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { EventControllerFindAll200Meta } from './eventControllerFindAll200Meta';
import type { EventResponseDto } from './eventResponseDto';

export type EventControllerFindAll200 = {
  data?: EventResponseDto[];
  meta?: EventControllerFindAll200Meta;
};
