/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { EventControllerFindAll200DataMeta } from './eventControllerFindAll200DataMeta';
import type { EventResponseDto } from './eventResponseDto';

export type EventControllerFindAll200Data = {
  data?: EventResponseDto[];
  meta?: EventControllerFindAll200DataMeta;
};
