/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Participant status
 */
export type EventParticipantStatus = typeof EventParticipantStatus[keyof typeof EventParticipantStatus];


export const EventParticipantStatus = {
  REGISTERED: 'REGISTERED',
  FINDING_PARTNER: 'FINDING_PARTNER',
  WAITING_PARTNER: 'WAITING_PARTNER',
  PAIRED: 'PAIRED',
  CHECKED_IN: 'CHECKED_IN',
  READY: 'READY',
  PLAYING: 'PLAYING',
  ELIMINATED: 'ELIMINATED',
  WINNER: 'WINNER',
  WITHDRAWN: 'WITHDRAWN',
  DISQUALIFIED: 'DISQUALIFIED',
} as const;
