/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { EventResponseDtoPaymentMethodsItem } from './eventResponseDtoPaymentMethodsItem';
import type { EventResponseDtoScoringConfig } from './eventResponseDtoScoringConfig';
import type { EventResponseDtoSportType } from './eventResponseDtoSportType';
import type { EventResponseDtoStatus } from './eventResponseDtoStatus';

export interface EventResponseDto {
  /** ID sự kiện */
  id: string;
  /** ID người tổ chức */
  organizerId: string;
  /** Tên sự kiện */
  name: string;
  /** Thương hiệu */
  brand?: string;
  /** Loại hình thể thao */
  sportType: EventResponseDtoSportType;
  /** Hotline hỗ trợ */
  hotline: string;
  /** Địa chỉ */
  address: string;
  /** Mã tỉnh/thành */
  provinceCode: string;
  /** Tên tỉnh/thành */
  provinceName?: string;
  /** Mã phường/xã */
  wardCode: string;
  /** Tên phường/xã */
  wardName?: string;
  /** Mã tiền tố */
  prefixCode: string;
  /** Slug URL */
  slug: string;
  /** Cho phép chuyển nhượng */
  allowTransfer: boolean;
  /** Trạng thái sự kiện */
  status: EventResponseDtoStatus;
  /** Thời gian bắt đầu */
  eventStartTime: string;
  /** Thời gian kết thúc */
  eventEndTime: string;
  /** Thời gian mở chỉnh sửa */
  editInfoOpenTime: string;
  /** Thời gian đóng chỉnh sửa */
  editInfoCloseTime: string;
  /** Thời gian mở chuyển nhượng */
  transferOpenTime?: string;
  /** Thời gian đóng chuyển nhượng */
  transferCloseTime?: string;
  /** Thời gian mở check-in */
  checkinOpenTime: string;
  /** Thời gian đóng check-in */
  checkinCloseTime: string;
  /** Phương thức thanh toán */
  paymentMethods: EventResponseDtoPaymentMethodsItem[];
  /** Cấu hình luật thi đấu */
  scoringConfig?: EventResponseDtoScoringConfig;
  /** Banner được bật */
  bannerEnabled: boolean;
  /** URL hình banner */
  bannerImageUrl?: string;
  /** Link CTA banner */
  bannerCtaUrl?: string;
  /** URL file điều khoản */
  termsFileUrl?: string;
  /** URL file điều kiện */
  conditionsFileUrl?: string;
  /** Ngày tạo */
  created_at: string;
  /** Ngày cập nhật */
  updated_at: string;
}
