/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Participant status
 */
export type EventParticipantStatus = typeof EventParticipantStatus[keyof typeof EventParticipantStatus];


export const EventParticipantStatus = {
  REGISTERED: 'REGISTERED',
  CHECKED_IN: 'CHECKED_IN',
  WITHDRAWN: 'WITHDRAWN',
  DISQUALIFIED: 'DISQUALIFIED',
} as const;
