/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface GenerateUsersDto {
  /**
   * Number of bot users to generate
   * @minimum 1
   * @maximum 100
   */
  count: number;
  /** Prefix for generated names (default: "Bot") */
  prefix?: string;
}
