/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface GuardianInfoDto {
  /** Họ và tên người giám hộ */
  fullName: string;
  /** Ngày sinh người giám hộ */
  dateOfBirth: string;
  /** Số CCCD / Hộ chiếu người giám hộ */
  identityCard: string;
  /** Email người giám hộ */
  email: string;
  /** Số điện thoại người giám hộ */
  phoneNumber: string;
  /** Mối quan hệ với người tham gia */
  relationship: string;
}
