/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Sport type
 */
export type LeaderboardSportType = typeof LeaderboardSportType[keyof typeof LeaderboardSportType];


export const LeaderboardSportType = {
  PICKLEBALL: 'PICKLEBALL',
  BADMINTON: 'BADMINTON',
} as const;
