/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { LeaderboardEntry } from './leaderboardEntry';
import type { LeaderboardSportType } from './leaderboardSportType';
import type { LeaderboardType } from './leaderboardType';

export interface Leaderboard {
  /** Leaderboard unique identifier */
  id: string;
  /** Leaderboard name */
  name: string;
  /** Leaderboard type */
  type: LeaderboardType;
  /** Sport type */
  sportType: LeaderboardSportType;
  /** Period for monthly/yearly leaderboards */
  period?: string;
  /** Event ID for event-specific leaderboards */
  eventId?: string;
  /** Start date */
  startDate: string;
  /** End date */
  endDate?: string;
  /** Active status */
  isActive: boolean;
  /** Description */
  description?: string;
  /** Leaderboard entries */
  entries: LeaderboardEntry[];
}
