/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export type LeaderboardControllerGetEntriesParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
};
