/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Leaderboard type
 */
export type LeaderboardType = typeof LeaderboardType[keyof typeof LeaderboardType];


export const LeaderboardType = {
  OVERALL: 'OVERALL',
  EVENT: 'EVENT',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
} as const;
