/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Point-by-point details
 */
export type MatchScoreDetails = { [key: string]: unknown };
