/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { EventSession } from './eventSession';
import type { MatchScore } from './matchScore';
import type { MatchStatus } from './matchStatus';
import type { MatchTeam1Score } from './matchTeam1Score';
import type { MatchTeam2Score } from './matchTeam2Score';

export interface Match {
  /** Match unique identifier */
  id: string;
  /** Event session ID */
  sessionId: string;
  /** Event session relationship */
  session: EventSession;
  /** Match name */
  name: string;
  /** Match number */
  matchNumber?: number;
  /** Round name */
  round?: string;
  /** Court number */
  courtNumber?: number;
  /** Scheduled time */
  scheduledTime: string;
  /** Start time */
  startTime?: string;
  /** End time */
  endTime?: string;
  /** Match status */
  status: MatchStatus;
  /** Team 1 Player 1 ID */
  team1Player1Id?: string;
  /** Team 1 Player 2 ID */
  team1Player2Id?: string;
  /** Team 2 Player 1 ID */
  team2Player1Id?: string;
  /** Team 2 Player 2 ID */
  team2Player2Id?: string;
  /** Team 1 name */
  team1Name?: string;
  /** Team 2 name */
  team2Name?: string;
  /** Team 1 score data */
  team1Score?: MatchTeam1Score;
  /** Team 2 score data */
  team2Score?: MatchTeam2Score;
  /** Winner team (1 or 2) */
  winnerTeam?: number;
  /** Match notes */
  notes?: string;
  /** Is bye match */
  isBye: boolean;
  /** Match scores */
  scores: MatchScore[];
}
