/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { ProvinceControllerGetProvinceDepth } from './provinceControllerGetProvinceDepth';

export type ProvinceControllerGetProvinceParams = {
/**
 * 2: kèm danh sách phường/xã
 */
depth?: ProvinceControllerGetProvinceDepth;
};
