/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export type ProvinceControllerGetProvinceDepth = typeof ProvinceControllerGetProvinceDepth[keyof typeof ProvinceControllerGetProvinceDepth];


export const ProvinceControllerGetProvinceDepth = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
