/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { EventResponseDto } from './eventResponseDto';
import type { PublicEventControllerFindAll200DataMeta } from './publicEventControllerFindAll200DataMeta';

export type PublicEventControllerFindAll200Data = {
  data?: EventResponseDto[];
  meta?: PublicEventControllerFindAll200DataMeta;
};
