/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** User email address (primary identifier) */
  email: string;
  /**
   * Password for the account (min 6 characters)
   * @minLength 6
   */
  password: string;
  /** Display name for the user */
  displayName?: string;
  /**
   * Tags for user categorization
   * @maxItems 10
   */
  tags?: string[];
}
