/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /**
   * Username for the new account
   * @minLength 3
   */
  username: string;
  /**
   * Password for the new account
   * @minLength 6
   */
  password: string;
}
