/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface RunnerInfoDto {
  /** Họ và tên đệm */
  lastName: string;
  /** Tên */
  firstName: string;
  phoneNumber: string;
  location?: string;
  national?: string;
  provinceCode?: string;
  dateOfBirth?: string;
  sizeShirt?: string;
  club?: string;
  nameInBib?: string;
  medicalInformationPhoneNumber?: string;
  medicalInformationName?: string;
  medicalInformation?: string;
  typeOfMedicine?: string;
  bloodType?: string;
}
