/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { BadmintonChangeEndsDto } from './badmintonChangeEndsDto';
import type { ScoringConfigDtoMatchFormat } from './scoringConfigDtoMatchFormat';
import type { ScoringConfigDtoScoringMode } from './scoringConfigDtoScoringMode';
import type { ScoringConfigDtoSportType } from './scoringConfigDtoSportType';

export interface ScoringConfigDto {
  /** Loại hình thể thao */
  sportType: ScoringConfigDtoSportType;
  /** Cơ chế tính điểm */
  scoringMode: ScoringConfigDtoScoringMode;
  /** Thể thức trận đấu */
  matchFormat: ScoringConfigDtoMatchFormat;
  /**
   * Điểm số để thắng 1 set (min: 11, max depends on sportType)
   * @minimum 11
   */
  pointsToWin: number;
  /** Yêu cầu thắng cách biệt 2 điểm */
  winByTwo: boolean;
  /**
   * Điểm trần (cap) - điểm tối đa để kết thúc ván
   * @minimum 1
   */
  pointCap?: number;
  /** Điểm đổi sân (Pickleball only, 0 = disabled) */
  switchEndsAt?: number;
  /** Cấu hình đổi sân (Badminton only) */
  changeEnds?: BadmintonChangeEndsDto;
}
