/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Thể thức trận đấu
 */
export type ScoringConfigDtoMatchFormat = typeof ScoringConfigDtoMatchFormat[keyof typeof ScoringConfigDtoMatchFormat];


export const ScoringConfigDtoMatchFormat = {
  '1_SET': '1_SET',
  BEST_OF_3: 'BEST_OF_3',
  BEST_OF_5: 'BEST_OF_5',
} as const;
