/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Cơ chế tính điểm
 */
export type ScoringConfigDtoScoringMode = typeof ScoringConfigDtoScoringMode[keyof typeof ScoringConfigDtoScoringMode];


export const ScoringConfigDtoScoringMode = {
  SIDE_OUT: 'SIDE_OUT',
  RALLY_POINT: 'RALLY_POINT',
} as const;
