/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface SessionResponseDto {
  /** ID hạng mục */
  id: string;
  /** ID sự kiện */
  eventId: string;
  /** Tên hạng mục */
  name: string;
  /** Thể thức thi đấu (SINGLES/DOUBLES) */
  competitionFormat: string;
  /** Yêu cầu partner */
  requirePartner: boolean;
  /** Thời gian bắt đầu */
  startTime: string;
  /** Thời gian kết thúc */
  endTime: string;
  /** Mã vé */
  ticketCode: string;
  /** URL hình vé */
  ticketImageUrl?: string;
  /** Bật kiểm tra rating */
  ratingCheckEnabled: boolean;
  /** Nguồn rating */
  ratingSources?: unknown[][];
  /** Rating tối thiểu */
  minRating?: number;
  /** Rating tối đa */
  maxRating?: number;
  /** Thứ tự hiển thị */
  sortOrder: number;
  /** Ngày tạo */
  created_at: string;
  /** Ngày cập nhật */
  updated_at: string;
}
