/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface TicketTierResponseDto {
  /** ID loại vé */
  id: string;
  /** ID hạng mục */
  sessionId: string;
  /** Tên loại vé */
  name: string;
  /** Vé miễn phí */
  isFree: boolean;
  /** Giá vé (VND) */
  price?: number;
  /** Tổng số vé */
  totalQuantity: number;
  /** Tối thiểu/đơn */
  minPerOrder: number;
  /** Tối đa/đơn */
  maxPerOrder: number;
  /** Hiển thị */
  isVisible: boolean;
  /** Ngày bắt đầu bán */
  saleStartTime: string;
  /** Ngày ngưng bán */
  saleEndTime: string;
  /** Thứ tự hiển thị */
  sortOrder: number;
  /** Ngày tạo */
  created_at: string;
  /** Ngày cập nhật */
  updated_at: string;
}
