/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface UpdateMatchDto {
  /** Event session ID */
  sessionId?: string;
  /** Match name */
  name?: string;
  /** Match number */
  matchNumber?: number;
  /** Round name */
  round?: string;
  /** Court number */
  courtNumber?: number;
  /** Scheduled time (ISO format) */
  scheduledTime?: string;
  /** Team 1 Player 1 ID */
  team1Player1Id?: string;
  /** Team 1 Player 2 ID */
  team1Player2Id?: string;
  /** Team 2 Player 1 ID */
  team2Player1Id?: string;
  /** Team 2 Player 2 ID */
  team2Player2Id?: string;
  /** Team 1 name */
  team1Name?: string;
  /** Team 2 name */
  team2Name?: string;
  /** Notes */
  notes?: string;
  /** Is bye match */
  isBye?: boolean;
}
