/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Thể thức thi đấu
 */
export type UpdateEventSessionDtoMatchType = typeof UpdateEventSessionDtoMatchType[keyof typeof UpdateEventSessionDtoMatchType];


export const UpdateEventSessionDtoMatchType = {
  SINGLES: 'SINGLES',
  DOUBLES: 'DOUBLES',
} as const;
