/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { UpdateCourtDtoStatus } from './updateCourtDtoStatus';

export interface UpdateCourtDto {
  /** Court name */
  name?: string;
  /** Court status */
  status?: UpdateCourtDtoStatus;
  /** Allowed session IDs for category filtering */
  allowedSessionIds?: string[];
}
