/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { UpdateEventSessionDtoMatchType } from './updateEventSessionDtoMatchType';
import type { UpdateEventSessionDtoRatingSourcesItem } from './updateEventSessionDtoRatingSourcesItem';

export interface UpdateEventSessionDto {
  /**
   * Tên hạng mục thi đấu
   * @maxLength 256
   */
  name?: string;
  /** Thể thức thi đấu */
  matchType?: UpdateEventSessionDtoMatchType;
  /** Yêu cầu có đối thủ/đồng đội (chỉ với Doubles) */
  requirePartner?: boolean;
  /** Thời gian bắt đầu nội dung thi đấu (ISO 8601) */
  startTime?: string;
  /** Thời gian kết thúc dự kiến (ISO 8601) */
  endTime?: string;
  /**
   * Mã vé (tối đa 3 ký tự, unique trong sự kiện)
   * @maxLength 3
   */
  ticketCode?: string;
  /** URL hình ảnh vé */
  ticketImageUrl?: string;
  /** Bật kiểm tra rating/trình độ */
  ratingCheckEnabled?: boolean;
  /** Nguồn tham chiếu rating (bắt buộc nếu ratingCheckEnabled=true) */
  ratingSources?: UpdateEventSessionDtoRatingSourcesItem[];
  /** Ngưỡng điểm tối thiểu (bắt buộc nếu ratingCheckEnabled=true) */
  minRating?: number;
  /** Ngưỡng điểm tối đa (bắt buộc nếu ratingCheckEnabled=true) */
  maxRating?: number;
}
