/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Loại hình thể thao
 */
export type UpdateEventDtoSportType = typeof UpdateEventDtoSportType[keyof typeof UpdateEventDtoSportType];


export const UpdateEventDtoSportType = {
  PICKLEBALL: 'PICKLEBALL',
  BADMINTON: 'BADMINTON',
} as const;
