/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { UpdateStageDtoConfig } from './updateStageDtoConfig';
import type { UpdateStageDtoStageType } from './updateStageDtoStageType';

export interface UpdateStageDto {
  /**
   * Stage name
   * @maxLength 256
   */
  name?: string;
  /** Stage type */
  stageType?: UpdateStageDtoStageType;
  /** Stage configuration (varies by type). Round Robin: { groupCount, advancePerGroup, playoffType }. Elimination: { seedingType }. Flex: {} */
  config?: UpdateStageDtoConfig;
  /** Sort order */
  sortOrder?: number;
}
