/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Mapping với trường DB người tham dự (unique trong event)
 */
export type UpdateCustomFieldDtoDbMapping = typeof UpdateCustomFieldDtoDbMapping[keyof typeof UpdateCustomFieldDtoDbMapping];


export const UpdateCustomFieldDtoDbMapping = {
  participantName: 'participantName',
  participantsFirstName: 'participantsFirstName',
  participantsLastName: 'participantsLastName',
  participantsDOB: 'participantsDOB',
  participantsGender: 'participantsGender',
  participantsEmail: 'participantsEmail',
  participantsPhone: 'participantsPhone',
  participantsRacekit: 'participantsRacekit',
  participantsPortrait: 'participantsPortrait',
  participantsId: 'participantsId',
  participantsAddress: 'participantsAddress',
  participantsCompany: 'participantsCompany',
  participantsNational: 'participantsNational',
  participantsQuestion: 'participantsQuestion',
  participantsNote: 'participantsNote',
  participantsCity: 'participantsCity',
} as const;
