/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

export interface WardDto {
  /** Tên phường/xã */
  name: string;
  /** Mã phường/xã */
  code: number;
  /** Loại đơn vị hành chính */
  division_type: string;
  /** Tên mã */
  codename: string;
  /** Mã tỉnh/thành phố */
  province_code: number;
}
