/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCustomFieldDto,
  CreateDescriptionDto,
  CreateEventDto,
  CreateEventSessionDto,
  CreateTicketTierDto,
  EventControllerAddCustomField201,
  EventControllerAddDescription201,
  EventControllerCancel200,
  EventControllerCreate201,
  EventControllerCreateSession201,
  EventControllerCreateTicketTier201,
  EventControllerFindAll200,
  EventControllerFindAllParams,
  EventControllerFindOne200,
  EventControllerGetBlacklist200,
  EventControllerGetCustomFields200,
  EventControllerGetScoringConfig200,
  EventControllerPublish200,
  EventControllerSaveScoringConfig200,
  EventControllerSetBlacklist200,
  EventControllerUpdate200,
  EventControllerUpdateCustomField200,
  EventControllerUpdateDescription200,
  EventControllerUpdateSession200,
  EventControllerUpdateTicketTier200,
  ReorderDto,
  ScoringConfigDto,
  SetBlacklistDto,
  UpdateCustomFieldDto,
  UpdateDescriptionDto,
  UpdateEventDto,
  UpdateEventSessionDto,
  UpdateTicketTierDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Tạo một sự kiện mới với trạng thái DRAFT
 * @summary Tạo mới sự kiện
 */
export type eventControllerCreateResponse201 = {
  data: EventControllerCreate201
  status: 201
}
    
export type eventControllerCreateResponseSuccess = (eventControllerCreateResponse201) & {
  headers: Headers;
};
;

export type eventControllerCreateResponse = (eventControllerCreateResponseSuccess)

export const getEventControllerCreateUrl = () => {


  

  return `/events`
}

export const eventControllerCreate = async (createEventDto: CreateEventDto, options?: RequestInit): Promise<eventControllerCreateResponse> => {
  
  return defaultMutator<eventControllerCreateResponse>(getEventControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createEventDto,)
  }
);}




export const getEventControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreate>>, TError,{data: CreateEventDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreate>>, TError,{data: CreateEventDto}, TContext> => {

const mutationKey = ['eventControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerCreate>>, {data: CreateEventDto}> = (props) => {
          const {data} = props ?? {};

          return  eventControllerCreate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerCreate>>>
    export type EventControllerCreateMutationBody = CreateEventDto
    export type EventControllerCreateMutationError = unknown

    /**
 * @summary Tạo mới sự kiện
 */
export const useEventControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreate>>, TError,{data: CreateEventDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerCreate>>,
        TError,
        {data: CreateEventDto},
        TContext
      > => {
      return useMutation(getEventControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * Lấy danh sách các sự kiện của người dùng (phân trang)
 * @summary Danh sách sự kiện
 */
export type eventControllerFindAllResponse200 = {
  data: EventControllerFindAll200
  status: 200
}
    
export type eventControllerFindAllResponseSuccess = (eventControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type eventControllerFindAllResponse = (eventControllerFindAllResponseSuccess)

export const getEventControllerFindAllUrl = (params?: EventControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/events?${stringifiedParams}` : `/events`
}

export const eventControllerFindAll = async (params?: EventControllerFindAllParams, options?: RequestInit): Promise<eventControllerFindAllResponse> => {
  
  return defaultMutator<eventControllerFindAllResponse>(getEventControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEventControllerFindAllQueryKey = (params?: EventControllerFindAllParams,) => {
    return [
    `/events`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getEventControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof eventControllerFindAll>>, TError = unknown>(params?: EventControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventControllerFindAll>>> = ({ signal }) => eventControllerFindAll(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof eventControllerFindAll>>>
export type EventControllerFindAllQueryError = unknown


export function useEventControllerFindAll<TData = Awaited<ReturnType<typeof eventControllerFindAll>>, TError = unknown>(
 params: undefined |  EventControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof eventControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerFindAll<TData = Awaited<ReturnType<typeof eventControllerFindAll>>, TError = unknown>(
 params?: EventControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof eventControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerFindAll<TData = Awaited<ReturnType<typeof eventControllerFindAll>>, TError = unknown>(
 params?: EventControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Danh sách sự kiện
 */

export function useEventControllerFindAll<TData = Awaited<ReturnType<typeof eventControllerFindAll>>, TError = unknown>(
 params?: EventControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Lấy thông tin chi tiết một sự kiện
 * @summary Chi tiết sự kiện
 */
export type eventControllerFindOneResponse200 = {
  data: EventControllerFindOne200
  status: 200
}
    
export type eventControllerFindOneResponseSuccess = (eventControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type eventControllerFindOneResponse = (eventControllerFindOneResponseSuccess)

export const getEventControllerFindOneUrl = (id: string,) => {


  

  return `/events/${id}`
}

export const eventControllerFindOne = async (id: string, options?: RequestInit): Promise<eventControllerFindOneResponse> => {
  
  return defaultMutator<eventControllerFindOneResponse>(getEventControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEventControllerFindOneQueryKey = (id: string,) => {
    return [
    `/events/${id}`
    ] as const;
    }

    
export const getEventControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof eventControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventControllerFindOne>>> = ({ signal }) => eventControllerFindOne(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof eventControllerFindOne>>>
export type EventControllerFindOneQueryError = unknown


export function useEventControllerFindOne<TData = Awaited<ReturnType<typeof eventControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof eventControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerFindOne<TData = Awaited<ReturnType<typeof eventControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof eventControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerFindOne<TData = Awaited<ReturnType<typeof eventControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Chi tiết sự kiện
 */

export function useEventControllerFindOne<TData = Awaited<ReturnType<typeof eventControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Cập nhật thông tin sự kiện
 * @summary Cập nhật sự kiện
 */
export type eventControllerUpdateResponse200 = {
  data: EventControllerUpdate200
  status: 200
}
    
export type eventControllerUpdateResponseSuccess = (eventControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type eventControllerUpdateResponse = (eventControllerUpdateResponseSuccess)

export const getEventControllerUpdateUrl = (id: string,) => {


  

  return `/events/${id}`
}

export const eventControllerUpdate = async (id: string,
    updateEventDto: UpdateEventDto, options?: RequestInit): Promise<eventControllerUpdateResponse> => {
  
  return defaultMutator<eventControllerUpdateResponse>(getEventControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateEventDto,)
  }
);}




export const getEventControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdate>>, TError,{id: string;data: UpdateEventDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdate>>, TError,{id: string;data: UpdateEventDto}, TContext> => {

const mutationKey = ['eventControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerUpdate>>, {id: string;data: UpdateEventDto}> = (props) => {
          const {id,data} = props ?? {};

          return  eventControllerUpdate(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerUpdate>>>
    export type EventControllerUpdateMutationBody = UpdateEventDto
    export type EventControllerUpdateMutationError = unknown

    /**
 * @summary Cập nhật sự kiện
 */
export const useEventControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdate>>, TError,{id: string;data: UpdateEventDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerUpdate>>,
        TError,
        {id: string;data: UpdateEventDto},
        TContext
      > => {
      return useMutation(getEventControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * Xóa sự kiện (chỉ khi ở trạng thái DRAFT)
 * @summary Xóa sự kiện
 */
export type eventControllerDeleteResponse204 = {
  data: void
  status: 204
}
    
export type eventControllerDeleteResponseSuccess = (eventControllerDeleteResponse204) & {
  headers: Headers;
};
;

export type eventControllerDeleteResponse = (eventControllerDeleteResponseSuccess)

export const getEventControllerDeleteUrl = (id: string,) => {


  

  return `/events/${id}`
}

export const eventControllerDelete = async (id: string, options?: RequestInit): Promise<eventControllerDeleteResponse> => {
  
  return defaultMutator<eventControllerDeleteResponse>(getEventControllerDeleteUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getEventControllerDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['eventControllerDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  eventControllerDelete(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerDelete>>>
    
    export type EventControllerDeleteMutationError = unknown

    /**
 * @summary Xóa sự kiện
 */
export const useEventControllerDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getEventControllerDeleteMutationOptions(options), queryClient);
    }
    /**
 * Chuyển sự kiện từ DRAFT sang PUBLISHED
 * @summary Xuất bản sự kiện
 */
export type eventControllerPublishResponse200 = {
  data: EventControllerPublish200
  status: 200
}
    
export type eventControllerPublishResponseSuccess = (eventControllerPublishResponse200) & {
  headers: Headers;
};
;

export type eventControllerPublishResponse = (eventControllerPublishResponseSuccess)

export const getEventControllerPublishUrl = (id: string,) => {


  

  return `/events/${id}/publish`
}

export const eventControllerPublish = async (id: string, options?: RequestInit): Promise<eventControllerPublishResponse> => {
  
  return defaultMutator<eventControllerPublishResponse>(getEventControllerPublishUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getEventControllerPublishMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerPublish>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerPublish>>, TError,{id: string}, TContext> => {

const mutationKey = ['eventControllerPublish'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerPublish>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  eventControllerPublish(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerPublishMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerPublish>>>
    
    export type EventControllerPublishMutationError = unknown

    /**
 * @summary Xuất bản sự kiện
 */
export const useEventControllerPublish = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerPublish>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerPublish>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getEventControllerPublishMutationOptions(options), queryClient);
    }
    /**
 * Hủy sự kiện (từ PUBLISHED hoặc LIVE)
 * @summary Hủy sự kiện
 */
export type eventControllerCancelResponse200 = {
  data: EventControllerCancel200
  status: 200
}
    
export type eventControllerCancelResponseSuccess = (eventControllerCancelResponse200) & {
  headers: Headers;
};
;

export type eventControllerCancelResponse = (eventControllerCancelResponseSuccess)

export const getEventControllerCancelUrl = (id: string,) => {


  

  return `/events/${id}/cancel`
}

export const eventControllerCancel = async (id: string, options?: RequestInit): Promise<eventControllerCancelResponse> => {
  
  return defaultMutator<eventControllerCancelResponse>(getEventControllerCancelUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getEventControllerCancelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCancel>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerCancel>>, TError,{id: string}, TContext> => {

const mutationKey = ['eventControllerCancel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerCancel>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  eventControllerCancel(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerCancelMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerCancel>>>
    
    export type EventControllerCancelMutationError = unknown

    /**
 * @summary Hủy sự kiện
 */
export const useEventControllerCancel = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCancel>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerCancel>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getEventControllerCancelMutationOptions(options), queryClient);
    }
    /**
 * Thêm một khối mô tả mới cho sự kiện
 * @summary Thêm mô tả sự kiện
 */
export type eventControllerAddDescriptionResponse201 = {
  data: EventControllerAddDescription201
  status: 201
}
    
export type eventControllerAddDescriptionResponseSuccess = (eventControllerAddDescriptionResponse201) & {
  headers: Headers;
};
;

export type eventControllerAddDescriptionResponse = (eventControllerAddDescriptionResponseSuccess)

export const getEventControllerAddDescriptionUrl = (id: string,) => {


  

  return `/events/${id}/descriptions`
}

export const eventControllerAddDescription = async (id: string,
    createDescriptionDto: CreateDescriptionDto, options?: RequestInit): Promise<eventControllerAddDescriptionResponse> => {
  
  return defaultMutator<eventControllerAddDescriptionResponse>(getEventControllerAddDescriptionUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDescriptionDto,)
  }
);}




export const getEventControllerAddDescriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerAddDescription>>, TError,{id: string;data: CreateDescriptionDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerAddDescription>>, TError,{id: string;data: CreateDescriptionDto}, TContext> => {

const mutationKey = ['eventControllerAddDescription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerAddDescription>>, {id: string;data: CreateDescriptionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  eventControllerAddDescription(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerAddDescriptionMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerAddDescription>>>
    export type EventControllerAddDescriptionMutationBody = CreateDescriptionDto
    export type EventControllerAddDescriptionMutationError = unknown

    /**
 * @summary Thêm mô tả sự kiện
 */
export const useEventControllerAddDescription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerAddDescription>>, TError,{id: string;data: CreateDescriptionDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerAddDescription>>,
        TError,
        {id: string;data: CreateDescriptionDto},
        TContext
      > => {
      return useMutation(getEventControllerAddDescriptionMutationOptions(options), queryClient);
    }
    /**
 * Cập nhật nội dung mô tả sự kiện
 * @summary Cập nhật mô tả
 */
export type eventControllerUpdateDescriptionResponse200 = {
  data: EventControllerUpdateDescription200
  status: 200
}
    
export type eventControllerUpdateDescriptionResponseSuccess = (eventControllerUpdateDescriptionResponse200) & {
  headers: Headers;
};
;

export type eventControllerUpdateDescriptionResponse = (eventControllerUpdateDescriptionResponseSuccess)

export const getEventControllerUpdateDescriptionUrl = (id: string,
    descId: string,) => {


  

  return `/events/${id}/descriptions/${descId}`
}

export const eventControllerUpdateDescription = async (id: string,
    descId: string,
    updateDescriptionDto: UpdateDescriptionDto, options?: RequestInit): Promise<eventControllerUpdateDescriptionResponse> => {
  
  return defaultMutator<eventControllerUpdateDescriptionResponse>(getEventControllerUpdateDescriptionUrl(id,descId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateDescriptionDto,)
  }
);}




export const getEventControllerUpdateDescriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateDescription>>, TError,{id: string;descId: string;data: UpdateDescriptionDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateDescription>>, TError,{id: string;descId: string;data: UpdateDescriptionDto}, TContext> => {

const mutationKey = ['eventControllerUpdateDescription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerUpdateDescription>>, {id: string;descId: string;data: UpdateDescriptionDto}> = (props) => {
          const {id,descId,data} = props ?? {};

          return  eventControllerUpdateDescription(id,descId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerUpdateDescriptionMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerUpdateDescription>>>
    export type EventControllerUpdateDescriptionMutationBody = UpdateDescriptionDto
    export type EventControllerUpdateDescriptionMutationError = unknown

    /**
 * @summary Cập nhật mô tả
 */
export const useEventControllerUpdateDescription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateDescription>>, TError,{id: string;descId: string;data: UpdateDescriptionDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerUpdateDescription>>,
        TError,
        {id: string;descId: string;data: UpdateDescriptionDto},
        TContext
      > => {
      return useMutation(getEventControllerUpdateDescriptionMutationOptions(options), queryClient);
    }
    /**
 * Xóa một khối mô tả
 * @summary Xóa mô tả
 */
export type eventControllerDeleteDescriptionResponse204 = {
  data: void
  status: 204
}
    
export type eventControllerDeleteDescriptionResponseSuccess = (eventControllerDeleteDescriptionResponse204) & {
  headers: Headers;
};
;

export type eventControllerDeleteDescriptionResponse = (eventControllerDeleteDescriptionResponseSuccess)

export const getEventControllerDeleteDescriptionUrl = (id: string,
    descId: string,) => {


  

  return `/events/${id}/descriptions/${descId}`
}

export const eventControllerDeleteDescription = async (id: string,
    descId: string, options?: RequestInit): Promise<eventControllerDeleteDescriptionResponse> => {
  
  return defaultMutator<eventControllerDeleteDescriptionResponse>(getEventControllerDeleteDescriptionUrl(id,descId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getEventControllerDeleteDescriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteDescription>>, TError,{id: string;descId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteDescription>>, TError,{id: string;descId: string}, TContext> => {

const mutationKey = ['eventControllerDeleteDescription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerDeleteDescription>>, {id: string;descId: string}> = (props) => {
          const {id,descId} = props ?? {};

          return  eventControllerDeleteDescription(id,descId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerDeleteDescriptionMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerDeleteDescription>>>
    
    export type EventControllerDeleteDescriptionMutationError = unknown

    /**
 * @summary Xóa mô tả
 */
export const useEventControllerDeleteDescription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteDescription>>, TError,{id: string;descId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerDeleteDescription>>,
        TError,
        {id: string;descId: string},
        TContext
      > => {
      return useMutation(getEventControllerDeleteDescriptionMutationOptions(options), queryClient);
    }
    /**
 * Thay đổi thứ tự hiển thị của các mô tả
 * @summary Sắp xếp lại mô tả
 */
export type eventControllerReorderDescriptionsResponse204 = {
  data: void
  status: 204
}
    
export type eventControllerReorderDescriptionsResponseSuccess = (eventControllerReorderDescriptionsResponse204) & {
  headers: Headers;
};
;

export type eventControllerReorderDescriptionsResponse = (eventControllerReorderDescriptionsResponseSuccess)

export const getEventControllerReorderDescriptionsUrl = (id: string,) => {


  

  return `/events/${id}/descriptions/reorder`
}

export const eventControllerReorderDescriptions = async (id: string,
    reorderDto: ReorderDto, options?: RequestInit): Promise<eventControllerReorderDescriptionsResponse> => {
  
  return defaultMutator<eventControllerReorderDescriptionsResponse>(getEventControllerReorderDescriptionsUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reorderDto,)
  }
);}




export const getEventControllerReorderDescriptionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerReorderDescriptions>>, TError,{id: string;data: ReorderDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerReorderDescriptions>>, TError,{id: string;data: ReorderDto}, TContext> => {

const mutationKey = ['eventControllerReorderDescriptions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerReorderDescriptions>>, {id: string;data: ReorderDto}> = (props) => {
          const {id,data} = props ?? {};

          return  eventControllerReorderDescriptions(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerReorderDescriptionsMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerReorderDescriptions>>>
    export type EventControllerReorderDescriptionsMutationBody = ReorderDto
    export type EventControllerReorderDescriptionsMutationError = unknown

    /**
 * @summary Sắp xếp lại mô tả
 */
export const useEventControllerReorderDescriptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerReorderDescriptions>>, TError,{id: string;data: ReorderDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerReorderDescriptions>>,
        TError,
        {id: string;data: ReorderDto},
        TContext
      > => {
      return useMutation(getEventControllerReorderDescriptionsMutationOptions(options), queryClient);
    }
    /**
 * Tạo một hạng mục thi đấu mới (ca thi đấu)
 * @summary Tạo hạng mục thi đấu
 */
export type eventControllerCreateSessionResponse201 = {
  data: EventControllerCreateSession201
  status: 201
}
    
export type eventControllerCreateSessionResponseSuccess = (eventControllerCreateSessionResponse201) & {
  headers: Headers;
};
;

export type eventControllerCreateSessionResponse = (eventControllerCreateSessionResponseSuccess)

export const getEventControllerCreateSessionUrl = (id: string,) => {


  

  return `/events/${id}/sessions`
}

export const eventControllerCreateSession = async (id: string,
    createEventSessionDto: CreateEventSessionDto, options?: RequestInit): Promise<eventControllerCreateSessionResponse> => {
  
  return defaultMutator<eventControllerCreateSessionResponse>(getEventControllerCreateSessionUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createEventSessionDto,)
  }
);}




export const getEventControllerCreateSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreateSession>>, TError,{id: string;data: CreateEventSessionDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreateSession>>, TError,{id: string;data: CreateEventSessionDto}, TContext> => {

const mutationKey = ['eventControllerCreateSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerCreateSession>>, {id: string;data: CreateEventSessionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  eventControllerCreateSession(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerCreateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerCreateSession>>>
    export type EventControllerCreateSessionMutationBody = CreateEventSessionDto
    export type EventControllerCreateSessionMutationError = unknown

    /**
 * @summary Tạo hạng mục thi đấu
 */
export const useEventControllerCreateSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreateSession>>, TError,{id: string;data: CreateEventSessionDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerCreateSession>>,
        TError,
        {id: string;data: CreateEventSessionDto},
        TContext
      > => {
      return useMutation(getEventControllerCreateSessionMutationOptions(options), queryClient);
    }
    /**
 * Cập nhật thông tin hạng mục thi đấu
 * @summary Cập nhật hạng mục thi đấu
 */
export type eventControllerUpdateSessionResponse200 = {
  data: EventControllerUpdateSession200
  status: 200
}
    
export type eventControllerUpdateSessionResponseSuccess = (eventControllerUpdateSessionResponse200) & {
  headers: Headers;
};
;

export type eventControllerUpdateSessionResponse = (eventControllerUpdateSessionResponseSuccess)

export const getEventControllerUpdateSessionUrl = (id: string,
    sessionId: string,) => {


  

  return `/events/${id}/sessions/${sessionId}`
}

export const eventControllerUpdateSession = async (id: string,
    sessionId: string,
    updateEventSessionDto: UpdateEventSessionDto, options?: RequestInit): Promise<eventControllerUpdateSessionResponse> => {
  
  return defaultMutator<eventControllerUpdateSessionResponse>(getEventControllerUpdateSessionUrl(id,sessionId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateEventSessionDto,)
  }
);}




export const getEventControllerUpdateSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateSession>>, TError,{id: string;sessionId: string;data: UpdateEventSessionDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateSession>>, TError,{id: string;sessionId: string;data: UpdateEventSessionDto}, TContext> => {

const mutationKey = ['eventControllerUpdateSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerUpdateSession>>, {id: string;sessionId: string;data: UpdateEventSessionDto}> = (props) => {
          const {id,sessionId,data} = props ?? {};

          return  eventControllerUpdateSession(id,sessionId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerUpdateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerUpdateSession>>>
    export type EventControllerUpdateSessionMutationBody = UpdateEventSessionDto
    export type EventControllerUpdateSessionMutationError = unknown

    /**
 * @summary Cập nhật hạng mục thi đấu
 */
export const useEventControllerUpdateSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateSession>>, TError,{id: string;sessionId: string;data: UpdateEventSessionDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerUpdateSession>>,
        TError,
        {id: string;sessionId: string;data: UpdateEventSessionDto},
        TContext
      > => {
      return useMutation(getEventControllerUpdateSessionMutationOptions(options), queryClient);
    }
    /**
 * Xóa một hạng mục thi đấu
 * @summary Xóa hạng mục thi đấu
 */
export type eventControllerDeleteSessionResponse204 = {
  data: void
  status: 204
}
    
export type eventControllerDeleteSessionResponseSuccess = (eventControllerDeleteSessionResponse204) & {
  headers: Headers;
};
;

export type eventControllerDeleteSessionResponse = (eventControllerDeleteSessionResponseSuccess)

export const getEventControllerDeleteSessionUrl = (id: string,
    sessionId: string,) => {


  

  return `/events/${id}/sessions/${sessionId}`
}

export const eventControllerDeleteSession = async (id: string,
    sessionId: string, options?: RequestInit): Promise<eventControllerDeleteSessionResponse> => {
  
  return defaultMutator<eventControllerDeleteSessionResponse>(getEventControllerDeleteSessionUrl(id,sessionId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getEventControllerDeleteSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteSession>>, TError,{id: string;sessionId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteSession>>, TError,{id: string;sessionId: string}, TContext> => {

const mutationKey = ['eventControllerDeleteSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerDeleteSession>>, {id: string;sessionId: string}> = (props) => {
          const {id,sessionId} = props ?? {};

          return  eventControllerDeleteSession(id,sessionId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerDeleteSessionMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerDeleteSession>>>
    
    export type EventControllerDeleteSessionMutationError = unknown

    /**
 * @summary Xóa hạng mục thi đấu
 */
export const useEventControllerDeleteSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteSession>>, TError,{id: string;sessionId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerDeleteSession>>,
        TError,
        {id: string;sessionId: string},
        TContext
      > => {
      return useMutation(getEventControllerDeleteSessionMutationOptions(options), queryClient);
    }
    /**
 * Tạo một loại vé mới cho hạng mục thi đấu
 * @summary Tạo loại vé
 */
export type eventControllerCreateTicketTierResponse201 = {
  data: EventControllerCreateTicketTier201
  status: 201
}
    
export type eventControllerCreateTicketTierResponseSuccess = (eventControllerCreateTicketTierResponse201) & {
  headers: Headers;
};
;

export type eventControllerCreateTicketTierResponse = (eventControllerCreateTicketTierResponseSuccess)

export const getEventControllerCreateTicketTierUrl = (id: string,
    sessionId: string,) => {


  

  return `/events/${id}/sessions/${sessionId}/tickets`
}

export const eventControllerCreateTicketTier = async (id: string,
    sessionId: string,
    createTicketTierDto: CreateTicketTierDto, options?: RequestInit): Promise<eventControllerCreateTicketTierResponse> => {
  
  return defaultMutator<eventControllerCreateTicketTierResponse>(getEventControllerCreateTicketTierUrl(id,sessionId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTicketTierDto,)
  }
);}




export const getEventControllerCreateTicketTierMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreateTicketTier>>, TError,{id: string;sessionId: string;data: CreateTicketTierDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreateTicketTier>>, TError,{id: string;sessionId: string;data: CreateTicketTierDto}, TContext> => {

const mutationKey = ['eventControllerCreateTicketTier'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerCreateTicketTier>>, {id: string;sessionId: string;data: CreateTicketTierDto}> = (props) => {
          const {id,sessionId,data} = props ?? {};

          return  eventControllerCreateTicketTier(id,sessionId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerCreateTicketTierMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerCreateTicketTier>>>
    export type EventControllerCreateTicketTierMutationBody = CreateTicketTierDto
    export type EventControllerCreateTicketTierMutationError = unknown

    /**
 * @summary Tạo loại vé
 */
export const useEventControllerCreateTicketTier = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreateTicketTier>>, TError,{id: string;sessionId: string;data: CreateTicketTierDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerCreateTicketTier>>,
        TError,
        {id: string;sessionId: string;data: CreateTicketTierDto},
        TContext
      > => {
      return useMutation(getEventControllerCreateTicketTierMutationOptions(options), queryClient);
    }
    /**
 * Cập nhật thông tin loại vé
 * @summary Cập nhật loại vé
 */
export type eventControllerUpdateTicketTierResponse200 = {
  data: EventControllerUpdateTicketTier200
  status: 200
}
    
export type eventControllerUpdateTicketTierResponseSuccess = (eventControllerUpdateTicketTierResponse200) & {
  headers: Headers;
};
;

export type eventControllerUpdateTicketTierResponse = (eventControllerUpdateTicketTierResponseSuccess)

export const getEventControllerUpdateTicketTierUrl = (id: string,
    sessionId: string,
    ticketId: string,) => {


  

  return `/events/${id}/sessions/${sessionId}/tickets/${ticketId}`
}

export const eventControllerUpdateTicketTier = async (id: string,
    sessionId: string,
    ticketId: string,
    updateTicketTierDto: UpdateTicketTierDto, options?: RequestInit): Promise<eventControllerUpdateTicketTierResponse> => {
  
  return defaultMutator<eventControllerUpdateTicketTierResponse>(getEventControllerUpdateTicketTierUrl(id,sessionId,ticketId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTicketTierDto,)
  }
);}




export const getEventControllerUpdateTicketTierMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateTicketTier>>, TError,{id: string;sessionId: string;ticketId: string;data: UpdateTicketTierDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateTicketTier>>, TError,{id: string;sessionId: string;ticketId: string;data: UpdateTicketTierDto}, TContext> => {

const mutationKey = ['eventControllerUpdateTicketTier'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerUpdateTicketTier>>, {id: string;sessionId: string;ticketId: string;data: UpdateTicketTierDto}> = (props) => {
          const {id,sessionId,ticketId,data} = props ?? {};

          return  eventControllerUpdateTicketTier(id,sessionId,ticketId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerUpdateTicketTierMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerUpdateTicketTier>>>
    export type EventControllerUpdateTicketTierMutationBody = UpdateTicketTierDto
    export type EventControllerUpdateTicketTierMutationError = unknown

    /**
 * @summary Cập nhật loại vé
 */
export const useEventControllerUpdateTicketTier = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateTicketTier>>, TError,{id: string;sessionId: string;ticketId: string;data: UpdateTicketTierDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerUpdateTicketTier>>,
        TError,
        {id: string;sessionId: string;ticketId: string;data: UpdateTicketTierDto},
        TContext
      > => {
      return useMutation(getEventControllerUpdateTicketTierMutationOptions(options), queryClient);
    }
    /**
 * Xóa một loại vé
 * @summary Xóa loại vé
 */
export type eventControllerDeleteTicketTierResponse204 = {
  data: void
  status: 204
}
    
export type eventControllerDeleteTicketTierResponseSuccess = (eventControllerDeleteTicketTierResponse204) & {
  headers: Headers;
};
;

export type eventControllerDeleteTicketTierResponse = (eventControllerDeleteTicketTierResponseSuccess)

export const getEventControllerDeleteTicketTierUrl = (id: string,
    sessionId: string,
    ticketId: string,) => {


  

  return `/events/${id}/sessions/${sessionId}/tickets/${ticketId}`
}

export const eventControllerDeleteTicketTier = async (id: string,
    sessionId: string,
    ticketId: string, options?: RequestInit): Promise<eventControllerDeleteTicketTierResponse> => {
  
  return defaultMutator<eventControllerDeleteTicketTierResponse>(getEventControllerDeleteTicketTierUrl(id,sessionId,ticketId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getEventControllerDeleteTicketTierMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteTicketTier>>, TError,{id: string;sessionId: string;ticketId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteTicketTier>>, TError,{id: string;sessionId: string;ticketId: string}, TContext> => {

const mutationKey = ['eventControllerDeleteTicketTier'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerDeleteTicketTier>>, {id: string;sessionId: string;ticketId: string}> = (props) => {
          const {id,sessionId,ticketId} = props ?? {};

          return  eventControllerDeleteTicketTier(id,sessionId,ticketId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerDeleteTicketTierMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerDeleteTicketTier>>>
    
    export type EventControllerDeleteTicketTierMutationError = unknown

    /**
 * @summary Xóa loại vé
 */
export const useEventControllerDeleteTicketTier = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteTicketTier>>, TError,{id: string;sessionId: string;ticketId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerDeleteTicketTier>>,
        TError,
        {id: string;sessionId: string;ticketId: string},
        TContext
      > => {
      return useMutation(getEventControllerDeleteTicketTierMutationOptions(options), queryClient);
    }
    /**
 * Lấy tất cả câu hỏi trong form đăng ký của sự kiện
 * @summary Danh sách trường dữ liệu tùy chỉnh
 */
export type eventControllerGetCustomFieldsResponse200 = {
  data: EventControllerGetCustomFields200
  status: 200
}
    
export type eventControllerGetCustomFieldsResponseSuccess = (eventControllerGetCustomFieldsResponse200) & {
  headers: Headers;
};
;

export type eventControllerGetCustomFieldsResponse = (eventControllerGetCustomFieldsResponseSuccess)

export const getEventControllerGetCustomFieldsUrl = (id: string,) => {


  

  return `/events/${id}/fields`
}

export const eventControllerGetCustomFields = async (id: string, options?: RequestInit): Promise<eventControllerGetCustomFieldsResponse> => {
  
  return defaultMutator<eventControllerGetCustomFieldsResponse>(getEventControllerGetCustomFieldsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEventControllerGetCustomFieldsQueryKey = (id: string,) => {
    return [
    `/events/${id}/fields`
    ] as const;
    }

    
export const getEventControllerGetCustomFieldsQueryOptions = <TData = Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventControllerGetCustomFieldsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventControllerGetCustomFields>>> = ({ signal }) => eventControllerGetCustomFields(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventControllerGetCustomFieldsQueryResult = NonNullable<Awaited<ReturnType<typeof eventControllerGetCustomFields>>>
export type EventControllerGetCustomFieldsQueryError = unknown


export function useEventControllerGetCustomFields<TData = Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerGetCustomFields>>,
          TError,
          Awaited<ReturnType<typeof eventControllerGetCustomFields>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerGetCustomFields<TData = Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerGetCustomFields>>,
          TError,
          Awaited<ReturnType<typeof eventControllerGetCustomFields>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerGetCustomFields<TData = Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Danh sách trường dữ liệu tùy chỉnh
 */

export function useEventControllerGetCustomFields<TData = Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetCustomFields>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventControllerGetCustomFieldsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Thêm một câu hỏi mới trong form đăng ký
 * @summary Thêm trường dữ liệu tùy chỉnh
 */
export type eventControllerAddCustomFieldResponse201 = {
  data: EventControllerAddCustomField201
  status: 201
}
    
export type eventControllerAddCustomFieldResponseSuccess = (eventControllerAddCustomFieldResponse201) & {
  headers: Headers;
};
;

export type eventControllerAddCustomFieldResponse = (eventControllerAddCustomFieldResponseSuccess)

export const getEventControllerAddCustomFieldUrl = (id: string,) => {


  

  return `/events/${id}/fields`
}

export const eventControllerAddCustomField = async (id: string,
    createCustomFieldDto: CreateCustomFieldDto, options?: RequestInit): Promise<eventControllerAddCustomFieldResponse> => {
  
  return defaultMutator<eventControllerAddCustomFieldResponse>(getEventControllerAddCustomFieldUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCustomFieldDto,)
  }
);}




export const getEventControllerAddCustomFieldMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerAddCustomField>>, TError,{id: string;data: CreateCustomFieldDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerAddCustomField>>, TError,{id: string;data: CreateCustomFieldDto}, TContext> => {

const mutationKey = ['eventControllerAddCustomField'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerAddCustomField>>, {id: string;data: CreateCustomFieldDto}> = (props) => {
          const {id,data} = props ?? {};

          return  eventControllerAddCustomField(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerAddCustomFieldMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerAddCustomField>>>
    export type EventControllerAddCustomFieldMutationBody = CreateCustomFieldDto
    export type EventControllerAddCustomFieldMutationError = unknown

    /**
 * @summary Thêm trường dữ liệu tùy chỉnh
 */
export const useEventControllerAddCustomField = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerAddCustomField>>, TError,{id: string;data: CreateCustomFieldDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerAddCustomField>>,
        TError,
        {id: string;data: CreateCustomFieldDto},
        TContext
      > => {
      return useMutation(getEventControllerAddCustomFieldMutationOptions(options), queryClient);
    }
    /**
 * Cập nhật thông tin câu hỏi trong form đăng ký
 * @summary Cập nhật trường dữ liệu
 */
export type eventControllerUpdateCustomFieldResponse200 = {
  data: EventControllerUpdateCustomField200
  status: 200
}
    
export type eventControllerUpdateCustomFieldResponseSuccess = (eventControllerUpdateCustomFieldResponse200) & {
  headers: Headers;
};
;

export type eventControllerUpdateCustomFieldResponse = (eventControllerUpdateCustomFieldResponseSuccess)

export const getEventControllerUpdateCustomFieldUrl = (id: string,
    fieldId: string,) => {


  

  return `/events/${id}/fields/${fieldId}`
}

export const eventControllerUpdateCustomField = async (id: string,
    fieldId: string,
    updateCustomFieldDto: UpdateCustomFieldDto, options?: RequestInit): Promise<eventControllerUpdateCustomFieldResponse> => {
  
  return defaultMutator<eventControllerUpdateCustomFieldResponse>(getEventControllerUpdateCustomFieldUrl(id,fieldId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCustomFieldDto,)
  }
);}




export const getEventControllerUpdateCustomFieldMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateCustomField>>, TError,{id: string;fieldId: string;data: UpdateCustomFieldDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateCustomField>>, TError,{id: string;fieldId: string;data: UpdateCustomFieldDto}, TContext> => {

const mutationKey = ['eventControllerUpdateCustomField'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerUpdateCustomField>>, {id: string;fieldId: string;data: UpdateCustomFieldDto}> = (props) => {
          const {id,fieldId,data} = props ?? {};

          return  eventControllerUpdateCustomField(id,fieldId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerUpdateCustomFieldMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerUpdateCustomField>>>
    export type EventControllerUpdateCustomFieldMutationBody = UpdateCustomFieldDto
    export type EventControllerUpdateCustomFieldMutationError = unknown

    /**
 * @summary Cập nhật trường dữ liệu
 */
export const useEventControllerUpdateCustomField = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerUpdateCustomField>>, TError,{id: string;fieldId: string;data: UpdateCustomFieldDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerUpdateCustomField>>,
        TError,
        {id: string;fieldId: string;data: UpdateCustomFieldDto},
        TContext
      > => {
      return useMutation(getEventControllerUpdateCustomFieldMutationOptions(options), queryClient);
    }
    /**
 * Xóa một câu hỏi (chỉ khi sự kiện ở trạng thái DRAFT)
 * @summary Xóa trường dữ liệu
 */
export type eventControllerDeleteCustomFieldResponse204 = {
  data: void
  status: 204
}
    
export type eventControllerDeleteCustomFieldResponseSuccess = (eventControllerDeleteCustomFieldResponse204) & {
  headers: Headers;
};
;

export type eventControllerDeleteCustomFieldResponse = (eventControllerDeleteCustomFieldResponseSuccess)

export const getEventControllerDeleteCustomFieldUrl = (id: string,
    fieldId: string,) => {


  

  return `/events/${id}/fields/${fieldId}`
}

export const eventControllerDeleteCustomField = async (id: string,
    fieldId: string, options?: RequestInit): Promise<eventControllerDeleteCustomFieldResponse> => {
  
  return defaultMutator<eventControllerDeleteCustomFieldResponse>(getEventControllerDeleteCustomFieldUrl(id,fieldId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getEventControllerDeleteCustomFieldMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteCustomField>>, TError,{id: string;fieldId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteCustomField>>, TError,{id: string;fieldId: string}, TContext> => {

const mutationKey = ['eventControllerDeleteCustomField'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerDeleteCustomField>>, {id: string;fieldId: string}> = (props) => {
          const {id,fieldId} = props ?? {};

          return  eventControllerDeleteCustomField(id,fieldId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerDeleteCustomFieldMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerDeleteCustomField>>>
    
    export type EventControllerDeleteCustomFieldMutationError = unknown

    /**
 * @summary Xóa trường dữ liệu
 */
export const useEventControllerDeleteCustomField = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteCustomField>>, TError,{id: string;fieldId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerDeleteCustomField>>,
        TError,
        {id: string;fieldId: string},
        TContext
      > => {
      return useMutation(getEventControllerDeleteCustomFieldMutationOptions(options), queryClient);
    }
    /**
 * Thay đổi thứ tự hiển thị của các câu hỏi
 * @summary Sắp xếp lại trường dữ liệu
 */
export type eventControllerReorderCustomFieldsResponse204 = {
  data: void
  status: 204
}
    
export type eventControllerReorderCustomFieldsResponseSuccess = (eventControllerReorderCustomFieldsResponse204) & {
  headers: Headers;
};
;

export type eventControllerReorderCustomFieldsResponse = (eventControllerReorderCustomFieldsResponseSuccess)

export const getEventControllerReorderCustomFieldsUrl = (id: string,) => {


  

  return `/events/${id}/fields/reorder`
}

export const eventControllerReorderCustomFields = async (id: string,
    reorderDto: ReorderDto, options?: RequestInit): Promise<eventControllerReorderCustomFieldsResponse> => {
  
  return defaultMutator<eventControllerReorderCustomFieldsResponse>(getEventControllerReorderCustomFieldsUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reorderDto,)
  }
);}




export const getEventControllerReorderCustomFieldsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerReorderCustomFields>>, TError,{id: string;data: ReorderDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerReorderCustomFields>>, TError,{id: string;data: ReorderDto}, TContext> => {

const mutationKey = ['eventControllerReorderCustomFields'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerReorderCustomFields>>, {id: string;data: ReorderDto}> = (props) => {
          const {id,data} = props ?? {};

          return  eventControllerReorderCustomFields(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerReorderCustomFieldsMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerReorderCustomFields>>>
    export type EventControllerReorderCustomFieldsMutationBody = ReorderDto
    export type EventControllerReorderCustomFieldsMutationError = unknown

    /**
 * @summary Sắp xếp lại trường dữ liệu
 */
export const useEventControllerReorderCustomFields = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerReorderCustomFields>>, TError,{id: string;data: ReorderDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerReorderCustomFields>>,
        TError,
        {id: string;data: ReorderDto},
        TContext
      > => {
      return useMutation(getEventControllerReorderCustomFieldsMutationOptions(options), queryClient);
    }
    /**
 * Thiết lập các luật tính điểm dựa trên loại thể thao
 * @summary Cấu hình luật thi đấu
 */
export type eventControllerSaveScoringConfigResponse200 = {
  data: EventControllerSaveScoringConfig200
  status: 200
}
    
export type eventControllerSaveScoringConfigResponseSuccess = (eventControllerSaveScoringConfigResponse200) & {
  headers: Headers;
};
;

export type eventControllerSaveScoringConfigResponse = (eventControllerSaveScoringConfigResponseSuccess)

export const getEventControllerSaveScoringConfigUrl = (id: string,) => {


  

  return `/events/${id}/scoring-config`
}

export const eventControllerSaveScoringConfig = async (id: string,
    scoringConfigDto: ScoringConfigDto, options?: RequestInit): Promise<eventControllerSaveScoringConfigResponse> => {
  
  return defaultMutator<eventControllerSaveScoringConfigResponse>(getEventControllerSaveScoringConfigUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      scoringConfigDto,)
  }
);}




export const getEventControllerSaveScoringConfigMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerSaveScoringConfig>>, TError,{id: string;data: ScoringConfigDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerSaveScoringConfig>>, TError,{id: string;data: ScoringConfigDto}, TContext> => {

const mutationKey = ['eventControllerSaveScoringConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerSaveScoringConfig>>, {id: string;data: ScoringConfigDto}> = (props) => {
          const {id,data} = props ?? {};

          return  eventControllerSaveScoringConfig(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerSaveScoringConfigMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerSaveScoringConfig>>>
    export type EventControllerSaveScoringConfigMutationBody = ScoringConfigDto
    export type EventControllerSaveScoringConfigMutationError = unknown

    /**
 * @summary Cấu hình luật thi đấu
 */
export const useEventControllerSaveScoringConfig = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerSaveScoringConfig>>, TError,{id: string;data: ScoringConfigDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerSaveScoringConfig>>,
        TError,
        {id: string;data: ScoringConfigDto},
        TContext
      > => {
      return useMutation(getEventControllerSaveScoringConfigMutationOptions(options), queryClient);
    }
    /**
 * Lấy thông tin cấu hình luật thi đấu của sự kiện
 * @summary Lấy cấu hình luật thi đấu
 */
export type eventControllerGetScoringConfigResponse200 = {
  data: EventControllerGetScoringConfig200
  status: 200
}
    
export type eventControllerGetScoringConfigResponseSuccess = (eventControllerGetScoringConfigResponse200) & {
  headers: Headers;
};
;

export type eventControllerGetScoringConfigResponse = (eventControllerGetScoringConfigResponseSuccess)

export const getEventControllerGetScoringConfigUrl = (id: string,) => {


  

  return `/events/${id}/scoring-config`
}

export const eventControllerGetScoringConfig = async (id: string, options?: RequestInit): Promise<eventControllerGetScoringConfigResponse> => {
  
  return defaultMutator<eventControllerGetScoringConfigResponse>(getEventControllerGetScoringConfigUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEventControllerGetScoringConfigQueryKey = (id: string,) => {
    return [
    `/events/${id}/scoring-config`
    ] as const;
    }

    
export const getEventControllerGetScoringConfigQueryOptions = <TData = Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventControllerGetScoringConfigQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventControllerGetScoringConfig>>> = ({ signal }) => eventControllerGetScoringConfig(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventControllerGetScoringConfigQueryResult = NonNullable<Awaited<ReturnType<typeof eventControllerGetScoringConfig>>>
export type EventControllerGetScoringConfigQueryError = unknown


export function useEventControllerGetScoringConfig<TData = Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerGetScoringConfig>>,
          TError,
          Awaited<ReturnType<typeof eventControllerGetScoringConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerGetScoringConfig<TData = Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerGetScoringConfig>>,
          TError,
          Awaited<ReturnType<typeof eventControllerGetScoringConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerGetScoringConfig<TData = Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lấy cấu hình luật thi đấu
 */

export function useEventControllerGetScoringConfig<TData = Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetScoringConfig>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventControllerGetScoringConfigQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Thay thế danh sách email/SĐT bị chặn
 * @summary Cập nhật danh sách chặn
 */
export type eventControllerSetBlacklistResponse200 = {
  data: EventControllerSetBlacklist200
  status: 200
}
    
export type eventControllerSetBlacklistResponseSuccess = (eventControllerSetBlacklistResponse200) & {
  headers: Headers;
};
;

export type eventControllerSetBlacklistResponse = (eventControllerSetBlacklistResponseSuccess)

export const getEventControllerSetBlacklistUrl = (id: string,) => {


  

  return `/events/${id}/blacklist`
}

export const eventControllerSetBlacklist = async (id: string,
    setBlacklistDto: SetBlacklistDto, options?: RequestInit): Promise<eventControllerSetBlacklistResponse> => {
  
  return defaultMutator<eventControllerSetBlacklistResponse>(getEventControllerSetBlacklistUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setBlacklistDto,)
  }
);}




export const getEventControllerSetBlacklistMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerSetBlacklist>>, TError,{id: string;data: SetBlacklistDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerSetBlacklist>>, TError,{id: string;data: SetBlacklistDto}, TContext> => {

const mutationKey = ['eventControllerSetBlacklist'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerSetBlacklist>>, {id: string;data: SetBlacklistDto}> = (props) => {
          const {id,data} = props ?? {};

          return  eventControllerSetBlacklist(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerSetBlacklistMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerSetBlacklist>>>
    export type EventControllerSetBlacklistMutationBody = SetBlacklistDto
    export type EventControllerSetBlacklistMutationError = unknown

    /**
 * @summary Cập nhật danh sách chặn
 */
export const useEventControllerSetBlacklist = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerSetBlacklist>>, TError,{id: string;data: SetBlacklistDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerSetBlacklist>>,
        TError,
        {id: string;data: SetBlacklistDto},
        TContext
      > => {
      return useMutation(getEventControllerSetBlacklistMutationOptions(options), queryClient);
    }
    /**
 * Lấy tất cả email/SĐT bị chặn
 * @summary Lấy danh sách chặn
 */
export type eventControllerGetBlacklistResponse200 = {
  data: EventControllerGetBlacklist200
  status: 200
}
    
export type eventControllerGetBlacklistResponseSuccess = (eventControllerGetBlacklistResponse200) & {
  headers: Headers;
};
;

export type eventControllerGetBlacklistResponse = (eventControllerGetBlacklistResponseSuccess)

export const getEventControllerGetBlacklistUrl = (id: string,) => {


  

  return `/events/${id}/blacklist`
}

export const eventControllerGetBlacklist = async (id: string, options?: RequestInit): Promise<eventControllerGetBlacklistResponse> => {
  
  return defaultMutator<eventControllerGetBlacklistResponse>(getEventControllerGetBlacklistUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEventControllerGetBlacklistQueryKey = (id: string,) => {
    return [
    `/events/${id}/blacklist`
    ] as const;
    }

    
export const getEventControllerGetBlacklistQueryOptions = <TData = Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventControllerGetBlacklistQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventControllerGetBlacklist>>> = ({ signal }) => eventControllerGetBlacklist(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventControllerGetBlacklistQueryResult = NonNullable<Awaited<ReturnType<typeof eventControllerGetBlacklist>>>
export type EventControllerGetBlacklistQueryError = unknown


export function useEventControllerGetBlacklist<TData = Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerGetBlacklist>>,
          TError,
          Awaited<ReturnType<typeof eventControllerGetBlacklist>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerGetBlacklist<TData = Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerGetBlacklist>>,
          TError,
          Awaited<ReturnType<typeof eventControllerGetBlacklist>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerGetBlacklist<TData = Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lấy danh sách chặn
 */

export function useEventControllerGetBlacklist<TData = Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetBlacklist>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventControllerGetBlacklistQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Add media to event
 */
export type eventControllerAddMediaResponse201 = {
  data: void
  status: 201
}
    
export type eventControllerAddMediaResponseSuccess = (eventControllerAddMediaResponse201) & {
  headers: Headers;
};
;

export type eventControllerAddMediaResponse = (eventControllerAddMediaResponseSuccess)

export const getEventControllerAddMediaUrl = (id: string,) => {


  

  return `/events/${id}/media`
}

export const eventControllerAddMedia = async (id: string, options?: RequestInit): Promise<eventControllerAddMediaResponse> => {
  
  return defaultMutator<eventControllerAddMediaResponse>(getEventControllerAddMediaUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getEventControllerAddMediaMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerAddMedia>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerAddMedia>>, TError,{id: string}, TContext> => {

const mutationKey = ['eventControllerAddMedia'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerAddMedia>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  eventControllerAddMedia(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerAddMediaMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerAddMedia>>>
    
    export type EventControllerAddMediaMutationError = unknown

    /**
 * @summary Add media to event
 */
export const useEventControllerAddMedia = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerAddMedia>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerAddMedia>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getEventControllerAddMediaMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete media from event
 */
export type eventControllerDeleteMediaResponse200 = {
  data: void
  status: 200
}
    
export type eventControllerDeleteMediaResponseSuccess = (eventControllerDeleteMediaResponse200) & {
  headers: Headers;
};
;

export type eventControllerDeleteMediaResponse = (eventControllerDeleteMediaResponseSuccess)

export const getEventControllerDeleteMediaUrl = (id: string,
    mediaId: string,) => {


  

  return `/events/${id}/media/${mediaId}`
}

export const eventControllerDeleteMedia = async (id: string,
    mediaId: string, options?: RequestInit): Promise<eventControllerDeleteMediaResponse> => {
  
  return defaultMutator<eventControllerDeleteMediaResponse>(getEventControllerDeleteMediaUrl(id,mediaId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getEventControllerDeleteMediaMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteMedia>>, TError,{id: string;mediaId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteMedia>>, TError,{id: string;mediaId: string}, TContext> => {

const mutationKey = ['eventControllerDeleteMedia'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerDeleteMedia>>, {id: string;mediaId: string}> = (props) => {
          const {id,mediaId} = props ?? {};

          return  eventControllerDeleteMedia(id,mediaId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerDeleteMediaMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerDeleteMedia>>>
    
    export type EventControllerDeleteMediaMutationError = unknown

    /**
 * @summary Delete media from event
 */
export const useEventControllerDeleteMedia = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerDeleteMedia>>, TError,{id: string;mediaId: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerDeleteMedia>>,
        TError,
        {id: string;mediaId: string},
        TContext
      > => {
      return useMutation(getEventControllerDeleteMediaMutationOptions(options), queryClient);
    }
    