/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CampaignOrderControllerExportExcelParams,
  CampaignOrderControllerFindAllParams,
  CreateOrderDto,
  CreateOrderResponseDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type campaignOrderControllerCreateResponse201 = {
  data: CreateOrderResponseDto
  status: 201
}
    
export type campaignOrderControllerCreateResponseSuccess = (campaignOrderControllerCreateResponse201) & {
  headers: Headers;
};
;

export type campaignOrderControllerCreateResponse = (campaignOrderControllerCreateResponseSuccess)

export const getCampaignOrderControllerCreateUrl = (campaignId: string,) => {


  

  return `/campaigns/${campaignId}/orders`
}

export const campaignOrderControllerCreate = async (campaignId: string,
    createOrderDto: CreateOrderDto, options?: RequestInit): Promise<campaignOrderControllerCreateResponse> => {
  
  return defaultMutator<campaignOrderControllerCreateResponse>(getCampaignOrderControllerCreateUrl(campaignId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrderDto,)
  }
);}




export const getCampaignOrderControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderControllerCreate>>, TError,{campaignId: string;data: CreateOrderDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignOrderControllerCreate>>, TError,{campaignId: string;data: CreateOrderDto}, TContext> => {

const mutationKey = ['campaignOrderControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignOrderControllerCreate>>, {campaignId: string;data: CreateOrderDto}> = (props) => {
          const {campaignId,data} = props ?? {};

          return  campaignOrderControllerCreate(campaignId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignOrderControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof campaignOrderControllerCreate>>>
    export type CampaignOrderControllerCreateMutationBody = CreateOrderDto
    export type CampaignOrderControllerCreateMutationError = unknown

    export const useCampaignOrderControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderControllerCreate>>, TError,{campaignId: string;data: CreateOrderDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignOrderControllerCreate>>,
        TError,
        {campaignId: string;data: CreateOrderDto},
        TContext
      > => {
      return useMutation(getCampaignOrderControllerCreateMutationOptions(options), queryClient);
    }
    export type campaignOrderControllerFindAllResponse200 = {
  data: void
  status: 200
}
    
export type campaignOrderControllerFindAllResponseSuccess = (campaignOrderControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type campaignOrderControllerFindAllResponse = (campaignOrderControllerFindAllResponseSuccess)

export const getCampaignOrderControllerFindAllUrl = (campaignId: string,
    params?: CampaignOrderControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/campaigns/${campaignId}/orders?${stringifiedParams}` : `/campaigns/${campaignId}/orders`
}

export const campaignOrderControllerFindAll = async (campaignId: string,
    params?: CampaignOrderControllerFindAllParams, options?: RequestInit): Promise<campaignOrderControllerFindAllResponse> => {
  
  return defaultMutator<campaignOrderControllerFindAllResponse>(getCampaignOrderControllerFindAllUrl(campaignId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignOrderControllerFindAllQueryKey = (campaignId: string,
    params?: CampaignOrderControllerFindAllParams,) => {
    return [
    `/campaigns/${campaignId}/orders`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getCampaignOrderControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError = unknown>(campaignId: string,
    params?: CampaignOrderControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignOrderControllerFindAllQueryKey(campaignId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignOrderControllerFindAll>>> = ({ signal }) => campaignOrderControllerFindAll(campaignId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(campaignId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignOrderControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof campaignOrderControllerFindAll>>>
export type CampaignOrderControllerFindAllQueryError = unknown


export function useCampaignOrderControllerFindAll<TData = Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError = unknown>(
 campaignId: string,
    params: undefined |  CampaignOrderControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignOrderControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof campaignOrderControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignOrderControllerFindAll<TData = Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError = unknown>(
 campaignId: string,
    params?: CampaignOrderControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignOrderControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof campaignOrderControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignOrderControllerFindAll<TData = Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError = unknown>(
 campaignId: string,
    params?: CampaignOrderControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCampaignOrderControllerFindAll<TData = Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError = unknown>(
 campaignId: string,
    params?: CampaignOrderControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignOrderControllerFindAllQueryOptions(campaignId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type campaignOrderControllerResendEmailResponse201 = {
  data: void
  status: 201
}
    
export type campaignOrderControllerResendEmailResponseSuccess = (campaignOrderControllerResendEmailResponse201) & {
  headers: Headers;
};
;

export type campaignOrderControllerResendEmailResponse = (campaignOrderControllerResendEmailResponseSuccess)

export const getCampaignOrderControllerResendEmailUrl = (campaignId: string,
    orderCode: string,) => {


  

  return `/campaigns/${campaignId}/orders/${orderCode}/resend-email`
}

export const campaignOrderControllerResendEmail = async (campaignId: string,
    orderCode: string, options?: RequestInit): Promise<campaignOrderControllerResendEmailResponse> => {
  
  return defaultMutator<campaignOrderControllerResendEmailResponse>(getCampaignOrderControllerResendEmailUrl(campaignId,orderCode),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getCampaignOrderControllerResendEmailMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderControllerResendEmail>>, TError,{campaignId: string;orderCode: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignOrderControllerResendEmail>>, TError,{campaignId: string;orderCode: string}, TContext> => {

const mutationKey = ['campaignOrderControllerResendEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignOrderControllerResendEmail>>, {campaignId: string;orderCode: string}> = (props) => {
          const {campaignId,orderCode} = props ?? {};

          return  campaignOrderControllerResendEmail(campaignId,orderCode,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignOrderControllerResendEmailMutationResult = NonNullable<Awaited<ReturnType<typeof campaignOrderControllerResendEmail>>>
    
    export type CampaignOrderControllerResendEmailMutationError = unknown

    export const useCampaignOrderControllerResendEmail = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderControllerResendEmail>>, TError,{campaignId: string;orderCode: string}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignOrderControllerResendEmail>>,
        TError,
        {campaignId: string;orderCode: string},
        TContext
      > => {
      return useMutation(getCampaignOrderControllerResendEmailMutationOptions(options), queryClient);
    }
    export type campaignOrderControllerFindOneResponse200 = {
  data: void
  status: 200
}
    
export type campaignOrderControllerFindOneResponseSuccess = (campaignOrderControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type campaignOrderControllerFindOneResponse = (campaignOrderControllerFindOneResponseSuccess)

export const getCampaignOrderControllerFindOneUrl = (campaignId: string,
    id: string,) => {


  

  return `/campaigns/${campaignId}/orders/${id}`
}

export const campaignOrderControllerFindOne = async (campaignId: string,
    id: string, options?: RequestInit): Promise<campaignOrderControllerFindOneResponse> => {
  
  return defaultMutator<campaignOrderControllerFindOneResponse>(getCampaignOrderControllerFindOneUrl(campaignId,id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignOrderControllerFindOneQueryKey = (campaignId: string,
    id: string,) => {
    return [
    `/campaigns/${campaignId}/orders/${id}`
    ] as const;
    }

    
export const getCampaignOrderControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError = unknown>(campaignId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignOrderControllerFindOneQueryKey(campaignId,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignOrderControllerFindOne>>> = ({ signal }) => campaignOrderControllerFindOne(campaignId,id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(campaignId && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignOrderControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof campaignOrderControllerFindOne>>>
export type CampaignOrderControllerFindOneQueryError = unknown


export function useCampaignOrderControllerFindOne<TData = Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError = unknown>(
 campaignId: string,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignOrderControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof campaignOrderControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignOrderControllerFindOne<TData = Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError = unknown>(
 campaignId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignOrderControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof campaignOrderControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignOrderControllerFindOne<TData = Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError = unknown>(
 campaignId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCampaignOrderControllerFindOne<TData = Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError = unknown>(
 campaignId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignOrderControllerFindOneQueryOptions(campaignId,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type campaignOrderControllerExportExcelResponse200 = {
  data: void
  status: 200
}
    
export type campaignOrderControllerExportExcelResponseSuccess = (campaignOrderControllerExportExcelResponse200) & {
  headers: Headers;
};
;

export type campaignOrderControllerExportExcelResponse = (campaignOrderControllerExportExcelResponseSuccess)

export const getCampaignOrderControllerExportExcelUrl = (campaignId: string,
    params?: CampaignOrderControllerExportExcelParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/campaigns/${campaignId}/orders/export/excel?${stringifiedParams}` : `/campaigns/${campaignId}/orders/export/excel`
}

export const campaignOrderControllerExportExcel = async (campaignId: string,
    params?: CampaignOrderControllerExportExcelParams, options?: RequestInit): Promise<campaignOrderControllerExportExcelResponse> => {
  
  return defaultMutator<campaignOrderControllerExportExcelResponse>(getCampaignOrderControllerExportExcelUrl(campaignId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCampaignOrderControllerExportExcelQueryKey = (campaignId: string,
    params?: CampaignOrderControllerExportExcelParams,) => {
    return [
    `/campaigns/${campaignId}/orders/export/excel`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getCampaignOrderControllerExportExcelQueryOptions = <TData = Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError = unknown>(campaignId: string,
    params?: CampaignOrderControllerExportExcelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignOrderControllerExportExcelQueryKey(campaignId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>> = ({ signal }) => campaignOrderControllerExportExcel(campaignId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(campaignId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignOrderControllerExportExcelQueryResult = NonNullable<Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>>
export type CampaignOrderControllerExportExcelQueryError = unknown


export function useCampaignOrderControllerExportExcel<TData = Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError = unknown>(
 campaignId: string,
    params: undefined |  CampaignOrderControllerExportExcelParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>,
          TError,
          Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignOrderControllerExportExcel<TData = Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError = unknown>(
 campaignId: string,
    params?: CampaignOrderControllerExportExcelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>,
          TError,
          Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>
        > , 'initialData'
      >, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignOrderControllerExportExcel<TData = Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError = unknown>(
 campaignId: string,
    params?: CampaignOrderControllerExportExcelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCampaignOrderControllerExportExcel<TData = Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError = unknown>(
 campaignId: string,
    params?: CampaignOrderControllerExportExcelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignOrderControllerExportExcel>>, TError, TData>>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignOrderControllerExportExcelQueryOptions(campaignId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




